#!/usr/bin/php
<?php
/*
 * Update the URL's of all blogs (run this after the blog URL configuration was changed)
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
    log_console('Updating all blog posts with the URL configuration "'.str_log($_CONFIG['blogs']['url']).'"', 'update_urls', 'white');

    load_libs('blogs');

    $r = sql_query('SELECT `id, `name`, `seoname`, `createdon`, `modifiedon`, `createdby`, `category` FROM `blogs_posts`');

    while($post = sql_fetch($r)){
        log_console('Updating blog post "'.str_log($post['seoname']).'"', 'updating');

        sql_query('UPDATE `blogs_posts`
                   SET    `url` = :url
                   WHERE  `id`  = :id',

                   array(':url' => blogs_post_url($post, $current_domain = true),
                         ':id'  => $id));
    }

    log_console('Updated all blog posts with the URL configuration "'.str_log($_CONFIG['blogs']['url']).'"', 'finished', 'white');

}catch(Exception $e){
    throw new lsException('scripts/blogs/update_urls: Failed', $e);
}
?>
