#!/usr/bin/php
<?php
/*
 * Update the URL's of all blogs (run this after the blog URL configuration was changed)
 */
require_once(dirname(__FILE__).'/../../../libs/startup.php');

try{
    log_console('Updating all blog post URLs', 'update_urls', 'white');

    load_libs('blogs');

    blogs_update_urls(isset_get($argv));

    log_console('Updated all blog posts with the URL configuration "'.str_log($_CONFIG['blogs']['url']).'"', 'finished', 'green');

}catch(Exception $e){
    throw new bException('scripts/blogs/update_urls: Failed', $e);
}
?>
