#!/usr/bin/php
<?php
/*
 * This script lists available users
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../../libs/startup.php');


try{
    right_or_redirect('admin,users');

    load_libs('user');

    $limit   = cfi(argument(0));

    $query   = 'SELECT    `users`.`id`,
                          `users`.`name`,
                          `users`.`username`,
                          `users`.`email`,
                          `users`.`status`,
                          `users`.`type`,
                          `users`.`role`,
                          `users_admin`.`name` IS NOT NULL AS `admin`,
                          `users_god`.`name`   IS NOT NULL AS `god`

                FROM      `users`

                LEFT JOIN `users_rights` AS `users_admin`
                ON        `users_admin`.`name`     = "admin"
                AND       `users_admin`.`users_id` = `users`.`id`

                LEFT JOIN `users_rights` AS `users_god`
                ON        `users_god`.`name`       = "admin"
                AND       `users_god`.`users_id`   = `users`.`id`';

    $execute = array();

    /*
     * Consider only users with a specific type as real users?
     */
    if($_CONFIG['users']['type_filter'] !== false){
        if($_CONFIG['users']['type_filter'] === null){
            $query           .= ' WHERE `users`.`type` IS NULL';

        }else{
            $query           .= ' WHERE `users`.`type` = :type';
            $execute[':type'] = $_CONFIG['users']['type_filter'];
        }
    }

    $r = sql_query($query.($limit ? ' LIMIT '.$limit : ''));

    if(!$r->rowCount()){
        log_console('There are currently no users registered', '', 'yellow');

    }else{
        log_console('#id    Username     Type       Role       Admin God Status     Real name                        Email                            ', '', 'white');

        while($user = sql_fetch($r)){
            log_console(str_size($user['id'], 6, ' ', true).' '.str_size($user['username'], 12).' '.str_size($user['type'], 10).' '.str_size($user['role'], 10).' '.str_size(($user['admin'] ? 'Yes' : ''), 5).' '.str_size(($user['god'] ? 'Yes' : ''), 3).' '.str_size(status($user['status']), 10).' '.str_size($user['name'], 32).' '.str_size($user['email'], 32), '', '');
        }
    }

}catch(Exception $e){
    throw new bException('base/users/list: Failed', $e);
}
?>
