#!/usr/bin/php
<?php
/*
 * This script can modify certain aspects of users
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../../libs/startup.php');


try{
    cli_rights('admin,users,modify');
    load_libs('user,validate');

    $user    = user_get(argument(0), 'id,name,username,email');
    $where   = ' WHERE  `id`   = :id';
    $execute = array(':id'    => $user['id']);
    $v       = new validate_form();

    if(!$user){
        $v->setError(tr('Specified user "%user%" does not exist', array('%user%' => str_log(argument(0)))));
    }



    /*
     * Consider only users with a specific type as real users?
     */
    if($_CONFIG['users']['type_filter'] !== false){
        if($_CONFIG['users']['type_filter'] === null){
            $where           .= ' AND `users`.`type` IS NULL';

        }else{
            $where           .= ' AND`users`.`type` = :type';
            $execute[':type'] = $_CONFIG['users']['type_filter'];
        }
    }

    /*
     * Modify what exactly?
     */
    if($execute[':value'] = argument('name', true)){
        /*
         * Modify the users real name
         */
        if(!$execute[':value']){
            $v->setError(tr('Specified username "%name%" is not valid, it should be more than 2 characters', array('%name%' => $execute[':value'])));

        }elseif(strlen($execute[':value']) >= 255){
            $v->setError(tr('Specified username "%name%" is not valid, it should be less than 255 characters', array('%name%' => $execute[':value'])));
        }

        $query = 'UPDATE `users`
                  SET    `name` = :value';

        log_console('Updating user real name to "'.str_log($execute[':value']).'"');
        $modified = true;

    }elseif($execute[':value'] = argument('username', true)){
        /*
         * Modify the users username
         */
        if(!$execute[':value']){
            $v->setError(tr('Specified username "%username%" is not valid, it should be more than 2 characters', array('%username%' => $execute[':value'])));

        }elseif(strlen($execute[':value']) >= 64){
            $v->setError(tr('Specified username "%username%" is not valid, it should be less than 64 characters', array('%username%' => $execute[':value'])));
        }

        $query = 'UPDATE `users`
                  SET    `username` = :value';

        log_console('Updating user name to "'.str_log($execute[':value']).'"');
        $modified = true;

    }elseif($execute[':value'] = argument('email', true)){
        /*
         * Modify the users email
         */
        $v->isValidEmail($execute[':value'], tr('Specified email "%email%" is not a valid email address', array('%email%' => $execute[':value'])));

        $query = 'UPDATE `users`
                  SET    `email` = :value';

        log_console('Updating user email to "'.str_log($execute[':value']).'"');
        $modified = true;

    }elseif($execute[':value'] = argument('status', true)){
        /*
         * Modify the users status
         */
        if(!$execute[':value']){
            $execute[':value'] = null;

        }elseif(strlen($execute[':value']) > 16){
            $v->setError(tr('Specified status "%status%" is not valid, it should be less than 16 characters', array('%status%' => $execute[':value'])));
        }

        $query = 'UPDATE `users`
                  SET    `status` = :value';

        log_console('Updating user status to "'.str_log($execute[':value']).'"');
        $modified = true;
    }

    if(!isset_get($modified)){
        log_console('Not modified anything for user "'.user_name($user).'"', 'finished', 'yellow');

    }else{
        $v->isValid();

        sql_query($query.$where, $execute);

        log_console('Finished modifying user "'.user_name($user).'"', 'finished', 'white');
    }

}catch(Exception $e){
    throw new bException('scripts/users/modify: Failed', $e);
}
?>
