#!/usr/bin/php
<?php
/*
 * This script can modify certain aspects of users
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../../libs/startup.php');


try{
    $user = right_or_redirect('admin,users,modify');

    load_libs('user');

    if(!$user = user_get(argument(0))){
        throw new bException('Specified user "'.str_log(argument(0)).'" does not exist', 'notexists');
    }

    $where   = 'WHERE  `id`   = :id';

    $execute = array(':value' => $value,
                     ':id'    => $user['id']);

    /*
     * Consider only users with a specific type as real users?
     */
    if($_CONFIG['users']['type_filter'] !== false){
        if($_CONFIG['users']['type_filter'] === null){
            $where           .= ' AND `users`.`type` IS NULL';

        }else{
            $where           .= ' AND`users`.`type` = :type';
            $execute[':type'] = $_CONFIG['users']['type_filter'];
        }
    }

    /*
     * Modify what exactly?
     */
    if($value = argument('name', true)){
        /*
         * Modify the users real name
         */
        sql_query('UPDATE `users`
                   SET    `name` = :value'.$where,

                   $execute);

        log_console('Updated real name to "'.str_log($value).'"', 'name', 'green');
        $modified = true;
    }

    if($value = argument('username', true)){
        /*
         * Modify the users username
         */
        sql_query('UPDATE `users`
                   SET    `username` = :value
                   WHERE  `id`       = :id'.$where,

                   $execute);

        log_console('Updated username to "'.str_log($value).'"', 'username', 'green');
        $modified = true;
    }

    if($value = argument('email', true)){
        /*
         * Modify the users email
         */
        sql_query('UPDATE `users`
                   SET    `email` = :value
                   WHERE  `id`    = :id'.$where,

                   $execute);

        log_console('Updated email to "'.str_log($value).'"', 'email', 'green');
        $modified = true;
    }

    if($value = argument('status', true)){
        /*
         * Modify the users status
         */
        sql_query('UPDATE `users`
                   SET    `status` = :value
                   WHERE  `id`     = :id'.$where,

                   $execute);

        log_console('Updated status to "'.str_log($value).'"', 'status', 'green');
        $modified = true;
    }

    if(!isset_get($modified)){
        log_console('Not modified anything for user "'.$user['email'].'"', 'finished', 'yellow');

    }else{
        log_console('Finished modifying user "'.$user['email'].'"', 'finished', 'white');
    }

}catch(Exception $e){
    throw new bException('scripts/users/modify: Failed', $e);
}
?>
