#!/usr/bin/php
<?php
/*
 * This script can force reset of user password to the specified value
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../../libs/startup.php');

try{
    cli_rights('admin,users,setpassword');

    if(count($argv) != 2){
        switch(count($argv)){
            case 0:
                throw new bException('No user and password specified');

            case 1:
                throw new bException('No password specified');

            default:
                throw new bException('Too many arguments specified, please specify only username (or email) and password');
        }
    }

    $username = argument(0);
    $password = argument(1);

    $r = sql_query('UPDATE `users`

                    SET    `password` = :password

                    WHERE  `username` = :username
                    OR     `email`    = :email',

                   array(':password' => password($password),
                         ':username' => $username,
                         ':email'    => $username));

    if(!$r->rowCount()){
        throw new bException('User "'.str_log($username).'" not found, or password was the same, and so not updated');
    }

    log_console('Updated password for user "'.str_log($username).'"', '', 'white');

}catch(Exception $e){
    throw new bException('scripts/base/users/setpassword: Failed', $e);
}
?>
