#!/usr/bin/php
<?php
/*
 * This script displays the current user
 */
$usage = "./scripts/users/whoami";

$help  = "This script displays the current user running the BASE script";

$quiet = true; # Set to false if no startup log messages should be displayed

require_once(dirname(__FILE__).'/../../../libs/startup.php');

try{
	cli_only();

    if(empty($_SESSION['user']['id'])){
        log_console(tr('0 "Nobody" ""', ''));

    }else{
        log_console($_SESSION['user']['id'].' "'.$_SESSION['user']['name'].'" "'.$_SESSION['user']['email'].'"', '');
    }

}catch(Exception $e){
    cli_error('scripts/users/whoami: Failed', $e);
}
?>
