#!/usr/bin/php
<?php
/*
 * This script can create new notification classes
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../../libs/startup.php');


try{
    $params['name']        = argument(0);
    $params['methods']     = argument(1);
    $params['status']      = argument('status', true);
    $params['description'] = argument('description', true);

    load_libs('notifications');
    notifications_classes_insert($params);

    log_console('Added notification class "'.str_log($params['name']).'"', null, 'white');

}catch(Exception $e){
    throw new lsException('scripts/notifications/create: Failed', $e);
}
?>
