#!/usr/bin/php
<?php
/*
 * This script lists available notification classes
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../../libs/startup.php');


try{
    cli_only();
    user_or_redirect();

    load_libs('user');

    $limit       = cfi(argument('limit', true));
    $showmembers = argument('members', true);

    if(empty($_SESSION['user']['admin'])){
        $users_id = $_SESSION['user']['id'];

    }else{
        if($user = argument('user', true)){
            $user     = user_get($user);
            $users_id = $user['id'];

        }else{
            $users_id = null;
        }
    }

    if($showmembers){
        /*
         * Show members of the specified notifications class
         */
        $where = array();

        if($arg = not_empty(argument('name', true), argument('id', true))){
            $where[] = ($arg ? (is_numeric($arg) ? '`notifications_classes`.`id` = '.$arg : '`notifications_classes`.`name` = "'.cfm($arg).'"') : '');
        }

        if($arg = (empty($_SESSION['user']['admin']) ? '`notifications_classes`.`addedby` = '.$_SESSION['user']['id'] : '')){
            $where[] = $arg;
        }

        $class = sql_get('SELECT `id`, `name`
                          FROM   `notifications_classes`'.
                          implode(',', $where));

        if(!$class){
            throw new ('notifications/list: Specified notification class "'.str_log($arg).'" does not exist', 'notexists');
        }

        $r = sql_query('SELECT    `users`.`name`,
                                  `users`.`email`,
                                  `users`.`username`,
                                  `notifications_classes`.`status`

                        FROM      `notifications_classes`

                        LEFT JOIN `notifications_members`
                        ON        `notifications_members`.`classes_id` = `notifications_classes`.`id`

                        LEFT JOIN `users`
                        ON        `users`.`id` = `notifications_classes`.`addedby` '.

                        ($users_id ? ' WHERE `notifications_classes`.`addedby` ' : '').($limit ? ' LIMIT '.$limit : ''));

        if(!$r->rowCount()){
            if(empty($_SESSION['user']['admin'])){
                log_console('You currently have no members registerd for this notification class', '', 'yellow');

            }else{
                if(!empty($user)){
                    log_console('There are currently no members regstered for notification class "'.str_log($class['name']).'"', '', 'yellow');

                }else{
                    log_console('There are currently no notification class members registered', '', 'yellow');
                }
            }

        }else{
            log_console('Notification class   Status     Member             Added by                         ', '', 'white');

            while($member = sql_fetch($r)){
                log_console(str_size($class['name'], 20).' '.str_size(status($member['status']), 10).' '.str_size(user_name($member), 18).' '.str_size(user_name($member), 32), '', '');
            }
        }

    }else{
        $r = sql_query('SELECT    `notifications_classes`.`id`,
                                  `notifications_classes`.`name` AS classname,
                                  `notifications_classes`.`description`,
                                  `notifications_classes`.`methods`,
                                  `notifications_classes`.`status`,

                                  `users`.`name`,
                                  `users`.`email`,
                                  `users`.`username`

                        FROM      `notifications_classes`

                        LEFT JOIN `users`
                        ON        `users`.`id` = `notifications_classes`.`addedby` '.

                        ($users_id ? ' WHERE `notifications_classes`.`addedby` ' : '').($limit ? ' LIMIT '.$limit : ''));

        if(!$r->rowCount()){
            if(empty($_SESSION['user']['admin'])){
                log_console('You currently have no notification classes registered', '', 'yellow');

            }else{
                if(!empty($user)){
                    log_console('There are currently no notification classes registered for user "'.user_name($user).'"', '', 'yellow');

                }else{
                    log_console('There are currently no notification classes registered', '', 'yellow');
                }
            }

        }else{
            log_console('#id    Name             Added by                         Status     Description', '', 'white');

            while($class = sql_fetch($r)){
                log_console(str_size($class['id'], 6, ' ', true).' '.str_size($class['classname'], 16).' '.str_size(user_name($class), 32).' '.str_size(status($class['status']), 10).' '.str_truncate($class['description'], 50), '', '');
            }
        }
    }

}catch(Exception $e){
    throw new ('base/notifications/list: Failed', $e);
}
?>
