#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
    cli_only();
    load_libs('test,file');

    /*
     * Empty command line arguments so that
     */
    $path     = ROOT.'scripts/tests/';
    $argv     = array();
    $skiplist = array('.',
                      '..',
                      '.test',
                      'all',
                      'empty'); // Empty is a template script, dont execute it!

    foreach(scandir($path) as $file){
        try{
            if(in_array($file, $skiplist)) continue;

            /*
             * Create temporary test file that does not contain the shell hashbang header
             */
            log_console(tr('Executing test ":test"', array(':test' => $file)), 'white');

            script_exec('tests/'.$file);

        }catch(Exception $e){
            log_console($e, 'warning/'.$e->getCode());
        }
    }

}catch(Exception $e){
    throw new bException('scripts/tests/all: Failed', $e);
}
?>
