#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
	cli_only();
	load_libs('test,file');

    foreach($argv as $arg){
        switch($arg){
            case 'all':
// :TODO: Implement
                break;
        }
    }

    /*
     * Empty command line arguments so that
     */
	$path     = ROOT.'scripts/tests/';
    $argv     = array();
    $skiplist = array('.',
                      '..',
                      '.test',
                      'all',
                      'empty'); // Empty is a template script, dont execute it!

    foreach(scandir($path) as $file){
        if(in_array($file, $skiplist)) continue;

		/*
		 * Create temporary test file that does not contain the shell hashbang header
		 */
		$test = file_delete($path.'.test');
		$test = file_copy_tree($path.$file, $test, "#!/usr/bin/php\n", '', '.php');

        log_console('Executing test "'.$file.'"', '', 'white');

        include($test);

		/*
		 * Cleanup temporary test file
		 */
		file_delete($test);
    }

}catch(Exception $e){
    throw new ('scripts/tests/all: Failed', $e);
}
?>
