#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
    cli_only();
    load_libs('test');

    test('emptyfunction()', 'Function call which should do blah blah', function(){
        try{
            if(emptyfunction('lkjerlkfwejf', 127)){
                throw new bException('Did not do blah blah');
            }

        }catch(Exception $e){
showdie($e);
        }
    });

    test_completed('empty()');



    /*
     * Completed system tests
     */
    test_completed('empty', 'library');

}catch(Exception $e){
    throw new bException('scripts/tests/empty: Failed', $e);
}
?>
