#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
$quiet=true;
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
    cli_only();
    load_libs('test,image');

    foreach($argv as $arg){
        switch($arg){
            case 'all':
// :TODO: Implement
                break;
        }
    }

}catch(Exception $e){
    throw new bException('scripts/tests/image: Failed', $e);
}
?>
