#!/usr/bin/php
<?php
/*
 * This test script tests UTF8 processing
 */
$usage = "./scripts/base/empty\n".
         "./scripts/base/empty option [option]\n";

$help  = "No help available";

//$quiet = false;

require_once(dirname(__FILE__).'/../../libs/startup.php');

cli_only();
load_libs('test');
showdie('THIS TEST SCRIPT HAS NOT YET BEEN IMPLENTED');

$examples = array(
    'Valid ASCII' => "a",
    'Valid 2 Octet Sequence' => "\xc3\xb1",
    'Invalid 2 Octet Sequence' => "\xc3\x28",
    'Invalid Sequence Identifier' => "\xa0\xa1",
    'Valid 3 Octet Sequence' => "\xe2\x82\xa1",
    'Invalid 3 Octet Sequence (in 2nd Octet)' => "\xe2\x28\xa1",
    'Invalid 3 Octet Sequence (in 3rd Octet)' => "\xe2\x82\x28",
    'Valid 4 Octet Sequence' => "\xf0\x90\x8c\xbc",
    'Invalid 4 Octet Sequence (in 2nd Octet)' => "\xf0\x28\x8c\xbc",
    'Invalid 4 Octet Sequence (in 3rd Octet)' => "\xf0\x90\x28\xbc",
    'Invalid 4 Octet Sequence (in 4th Octet)' => "\xf0\x28\x8c\x28",
    'Valid 5 Octet Sequence (but not Unicode!)' => "\xf8\xa1\xa1\xa1\xa1",
    'Valid 6 Octet Sequence (but not Unicode!)' => "\xfc\xa1\xa1\xa1\xa1\xa1"
);


foreach($argv as $arg){
    switch($arg){
        case 'all':
// :TODO: Implement
            break;
    }
}

test('emptyfunction()', 'Function call which should do blah blah', function(){
    try{
        if(emptyfunction('lkjerlkfwejf', 127)){
            throw new bException('Did not do blah blah');
        }

    }catch(Exception $e){
showdie($e);
    }
});

test_completed('empty()');


// Completed system tests
test_completed('empty', 'library');
?>
