<?php
// Deploy target environments configuration

$_CONFIG['deploy']['trial']      = array('target_user'         => 'base',
                                         'target_server'       => 'trial.localhost',
                                         'target_port'         => 22,
                                         'target_dir'          => '/var/www/projects/base/',
                                         'target_dir'          => '/var/www/projects/base/',
                                         'categories'          => 'trial',
                                         'exclude_dirs'        => array('.git',
                                                                        'www/avatars/*',
                                                                        'www/logos/*',
                                                                        'www/photos/*',
                                                                        'www/headers/*',
                                                                        'www/streetview_cache/*',
                                                                        'www/tmp_photos/*',
                                                                        'data/xapian/*',
                                                                        'data/tmp',
                                                                        'data/content',
                                                                        'data/cache',
                                                                        'data/backups'),
                                         'languages'           => array('es'),
                                         'sudo'                => true,
                                         'user'                => 'apache',
                                         'group'               => 'apache',
                                         'dir_mode'            => 'ug+rwx,g+s,o-rwx',
                                         'file_mode'           => 'ug-x+rw,o-rwx',
                                         'www_mode'            => 'ug-w');

$_CONFIG['deploy']['production'] = array('target_user'         => 'base',
                                         'target_server'       => 'production.localhost',
                                         'target_port'         => 22,
                                         'target_dir'          => '/var/www/projects/base/',
                                         'categories'          => 'production',
                                         'exclude_dirs'        => array('.git',
                                                                        'www/avatars/*',
                                                                        'www/logos/*',
                                                                        'www/photos/*',
                                                                        'www/headers/*',
                                                                        'www/streetview_cache/*',
                                                                        'www/tmp_photos/*',
                                                                        'data/xapian/*',
                                                                        'data/tmp',
                                                                        'data/content',
                                                                        'data/cache',
                                                                        'data/backups'),
                                         'languages'           => array('es'),
                                         'sudo'                => true,
                                         'user'                => 'apache',
                                         'group'               => 'apache',
                                         'dir_mode'            => 'ug+rwx,g+s,o-rwx',
                                         'file_mode'           => 'ug-x+rw,o-rwx',
                                         'www_mode'            => 'ug-w');
?>
