<?php
/*
 * PHPDOC library
 *
 * This library is a front-end library for the phpdocumenter system used for documenting BASE projects
 *
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Sven Oostenbrink <support@capmega.com>
 */



/*
 * Initialize the library, automatically executed by libs_load()
 *
 * NOTE: This function is executed automatically by the load_libs() function and does not need to be called manually
 *
 * @author Sven Olaf Oostenbrink <sven@capmega.com>
 * @copyright Copyright (c) 2018 Capmega
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @category Function reference
 * @package
 *
 * @param
 * @return
 */
function phpdoc_library_init(){
    try{
        ensure_installed(array('name'      => 'phpdoc',
                               'project'   => 'phpdoc',
                               'callback'  => 'phpdoc_install',
                               'checks'    => array(ROOT.'libs/external/phpdoc/')));

    }catch(Exception $e){
        throw new bException('phpdoc_library_init(): Failed', $e);
    }
}



/*
 * Install the PHP documenter package
 *
 * NOTE: This function is executed automatically by the phpdoc_library_init() function and does not need to be called manually
 *
 * @author Sven Olaf Oostenbrink <sven@capmega.com>
 * @copyright Copyright (c) 2018 Capmega
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @category Function reference
 * @package
 *
 * @param
 * @return
 */
function phpdoc_install($params){
    try{
        $params['methods'] = array('pear' => array('channel-discover' => 'pear.phpdoc.org',
                                                   'install'          => 'phpdoc/phpDocumentor'));

        return install($params);

    }catch(Exception $e){
        throw new bException('phpdoc_install(): Failed', $e);
    }
}



/*
 * Have PHPDoc parse the specified path
 *
 * @author Sven Olaf Oostenbrink <sven@capmega.com>
 * @copyright Copyright (c) 2018 Capmega
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @category Function reference
 * @package phpdoc
 *
 * @param string $path The path that should be parsed
 * @return array the output generated by the phpdoc command
 */
function phpdoc_parse_path($path){
    try{
        return safe_exec('phpdoc parse "'.$path.'"');

    }catch(Exception $e){
        throw new bException('phpdoc_parse_path(): Failed', $e);
    }
}



?>
