#!/usr/bin/php
<?php
/*
 * This is the backup script
 *
 * @copyright Sven Oostenbrink <support@ingiga.com>
 */
$usage = "backup database mysql username USERNAME password PASSWORD [database DATABASE]\n".
         "backup path PATH\n".
         "backup sync SOURCE DESTINATION\n".
         "backup default\n".
         "backup (same as backup default)\n";
         "backup clean|clear\n";

$help  = "The backup script can create (zipped) backups of directory trees, and databases, and / or sync them with a remote localtion. It currently only supports MySQL databases";

require_once(__DIR__.'/../../libs/startup.php');

load_libs('backup');

$sync  = cli_argument('sync');
$mysql = cli_argument('mysql');
$path  = cli_argument('path', true);
$clear = cli_argument('clean') or cli_argument('clear');

if($mysql){
    $params['username'] = cli_argument('--username', true);
    $params['password'] = cli_argument('--password', true);
    $params['database'] = cli_argument('--database', true, true);
}

if($sync){
    $source = cli_argument('--source');
    $target = cli_argument('--target');
}

cli_no_arguments_left();

$params['date'] = new DateTime();

log_console(tr('Started backup with datetime stamp ":date"', array(':date' => date_convert($params['date']))), 'start', 'white');

if($mysql){
    $do     = true;
    $target = backup_mysql($params);

    log_console(tr('Finished MySQL backup to ":target"', array(':target' => $target)), 'green');
}

if($params['path'] = $path){
    /*
     *
     */
    $do     = true;
    $target = backup_path($params);

    log_console(tr('Finished path backup'), 'green');
}

if($sync){
    /*
     *
     */
    $params['source'] = $source;
    $params['target'] = $target;

    $do     = true;
    $target = backup_sync($params);

    log_console(tr('Finished backup sync from ":source" to ":destination"', array(':source' => $params['source'], ':destination' => $params['destination'])), 'green');
}

if($clear){
    /*
     *
     */
    $do     = true;
    $target = backups_cleanup(array());

    log_console(tr('Finished backup clear on ":target"', array(':target' => $target)), 'green');
}

if(empty($do)){
    throw new bException('No methods specified.', 'not-specified');
}
?>
