#!/usr/bin/php
<?php
/*
 * This script will simply decode base64 strings
 */
$usage = "./scripts/base/base64decode\n".
         "./scripts/base/base64decode BASE64CODE\n";

$help  = "This script will decode base64 strings and show the contents.";

require_once(__DIR__.'/../../libs/startup.php');

$string = cli_argument(0);
cli_no_arguments_left();

if(!$string){
    throw new bException(tr('No base64 string specified'), 'not-specified');
}

showdie(str_safe_base64_decode($string));
?>
