#!/usr/bin/php
<?php
/*
* This is an empty test script template
*/
$usage = "./scripts/cdn\n".
         "./scripts/cdn command \n";
         "./scripts/cdn option [option]\n";

$help  = "CDN management script

METHODS

command                        -

process                        -

ping                           -

info                           -

remove                         -

balance                        -

clean                          -

validate                       -

move                           -

OPTIONS
";

require_once(dirname(__FILE__).'/../../libs/startup.php');
load_libs('cdn');

cli_only();
cli_exclusive();

switch(cli_method()){
    case 'command':
        $command = cli_argument(1);
        $data    = cli_argument(2);
        $servers = cli_argument(3);

        cli_no_arguments_left();

        cdn_commands_send($command, $data, $servers);
        break;

    case 'process':
        $limit = cli_argument('--limit', true, cli_argument('-l', true));
        cli_no_arguments_left();

        cdn_commands_process($limit);
        break;

    case 'ping':
        $servers = arguments();
        cdn_ping($servers);
        break;

    case 'info':
        cli_no_arguments_left();

        /*
         * Show howmany listings and users are on each CDN server
         */
        log_console(tr('AVAILABE CDN SERVERS:'), '', 'white');

        foreach($_CONFIG['cdn']['servers'] as $server){
            log_console(cdn_prefix($server));
        }

        log_console('');
        log_console('CDN SERVER LISTING INFORMATION:', '', 'white');

        $list   = sql_list('SELECT `cdn`, COUNT(`id`) FROM `listings` GROUP BY `cdn`');

        $images = sql_list('SELECT    `listings`.`cdn`,
                                      COUNT(`images`.`id`)

                            FROM      `images`

                            LEFT JOIN `listings`
                            ON        `listings`.`id` = `images`.`listings_id`

                            GROUP BY  `cdn`');

        $videos = sql_list('SELECT    `listings`.`cdn`,
                                      COUNT(`videos`.`id`)

                            FROM      `videos`

                            LEFT JOIN `listings`
                            ON        `listings`.`id` = `videos`.`listings_id`

                            GROUP BY  `cdn`');

        $total['listings'] = array_sum($list);
        $total['images']   = array_sum($images);
        $total['videos']   = array_sum($videos);

        /*
         * Ensure that all CDN servers are displayed, also the ones that do not yet
         * have any listings
         */
        foreach($_CONFIG['cdn']['servers'] as $server){
            if(!isset($list[$server])){
                $list[$server] = 0;
            }
        }

        ksort($list);

        log_console(tr('CDN#      LISTING COUNT      IMAGE COUNT     VIDEOS COUNT'), '', 'cyan');

        foreach($list as $cdn => $count){
           if(!in_array($cdn, $_CONFIG['cdn']['servers'])){
               log_console(str_size($cdn, 4).'   '.str_size($count, 16, ' ', true).' '.str_size(isset_get($images[$cdn], 0), 16, ' ', true).' '.str_size(isset_get($videos[$cdn], 0), 16, ' ', true).'     NOT CONFIGURED!', '', 'yellow');

           }else{
               log_console(str_size($cdn, 4).'   '.str_size($count, 16, ' ', true).' '.str_size(isset_get($images[$cdn], 0), 16, ' ', true).' '.str_size(isset_get($videos[$cdn], 0), 16, ' ', true));
           }
        }

        log_console('Total  '.str_size($total['listings'], 16, ' ', true).' '.str_size(isset_get($total['images'], 0), 16, ' ', true).' '.str_size(isset_get($total['videos'], 0), 16, ' ', true), '', 'green');
        break;

    case 'remove':
        /*
         * Disable specified CDN server by moving all files away from it
         */
        $server = cli_argument(1);
        cli_no_arguments_left();

        cdn_remove($server);
        break;

    case 'balance':
        /*
         * Ensure that all CDN servers support more or less the same amount of listings and users
         */
        cli_no_arguments_left();
        cdn_balance();
        break;

    case 'clean':
        /*
         * Remove image links in the database if the linked files no longer exist.
         */
        cli_no_arguments_left();
        cdn_clean();
        break;

    case 'validate':
        /*
         * Validate either one listing or all listings, ensure that all files are available
         * on the specified CDN server
         */
        load_libs('curl');

        $listing = cli_argument(1);
        cli_no_arguments_left();

        if($listing){
            if(!is_numeric($listing)){
                throw new bException(tr('Invalid listing ":listing" specified', array(':listing' => $listing)), 'invalid');
            }

            $r = sql_query('SELECT `id`, `status`, `cdn` FROM `listings` WHERE `id` = :id', array(':id' => $listing));

            if(!$r->rowCount()){
                throw new bException(tr('Listing ":listing" does not exist', array(':listing' => $listing)), 'not-exist');
            }

        }else{
            $r = sql_query('SELECT `id`, `status`, `cdn` FROM `listings`');
        }

        cli_log(tr('Listings id Status           cdn Result'), 'cyan');

        $count = $r->rowCount();

        while($listing = sql_fetch($r)){
            $success = 0;
            $fail    = 0;

            unset($result);

            if($listing['status'] !== null){
                $color  = 'yellow';
                $result = 'NOT TESTED';

            }else{
                $color  = 'green';
                $images = sql_query('SELECT `file` FROM `images` WHERE `listings_id` = :listings_id', array(':listings_id' => $listing['id']));

                while($image = sql_fetch($images)){
                    try{
                        $ch = curl_get(array('method' => 'head',
                                             'proxy'  => false,
                                             'sleep'  => 0,
                                             'url'    => c_url_image($listing['id'], $image['file'], $listing['cdn'])));

                        $success++;

                    }catch(Exception $e){
                        $color = 'red';
                        $fail++;

                        switch($e->getCode()){
                            case 'http404':
                                $result[] = 'NOT FOUND';
                                break;

                            default:
                                $result[] = tr('ERROR ":error"', array(':error' => $e->getMessage()));

                        }
                    }
                }

                if(empty($result)){
                    $result[] = '200 OK';
                }

                $result = '[ '.str_size($success, 2, ' ', true).' / '.str_size($fail, 2, ' ', true).' ] '.implode(', ', $result);
            }

            cli_log(str_size($listing['id'], 11, ' ', true).' '.str_size($listing['status'], 17).str_size($listing['cdn'], 3, ' ', true).' '.$result, $color);
        }

        cli_log(tr('Processed ":count" listings', array(':count' => $count)), 'green');
        break;

    case 'move':
        /*
         * Move the files from specified listing to the specified CDN server
         */
        $listings_id = cli_argument('listing');
        $cdn         = cli_argument('cdn');
        cli_no_arguments_left();

        if(!$cdn){
            throw new bException(tr('No CDN specified'), 'not-specified');
        }

        if(!is_numeric($cdn)){
            throw new bException(tr('Invalid CDN ":cdn" specified, must be numeric', array(':cdn' => $cdn)), 'invalid');
        }

        if(!in_array($cdn, $_CONFIG['cdn']['servers'])){
            throw new bException(tr('Non existing CDN ":cdn" specified, must be one of ":list"', array(':cdn' => $cdn, ':list' => implode(',', $_CONFIG['cdn']['servers']))), 'not-exist');
        }

        if($cdn == $_CONFIG['cdn']['this']){
            throw new bException(tr('Cannot move files to CDN ":cdn", because that is the current CDN server', array(':cdn' => $cdn)), 'not-exist');
        }

        if(!$listings_id){
            throw new bException(tr('No listing specified'), 'not-specified');
        }

        $listing = sql_get('SELECT `id`, `cdn` FROM `listings` WHERE `id` = :id', array(':id' => $listings_id));

        if(!$listing){
            throw new bException(tr('Non existing listing ":listing" specified', array(':listing' => $listings_id)), 'not-exist');
        }

        if($listing['cdn'] == $cdn){
            throw new bException(tr('Listing ":listing" already has its files on cdn ":cdn"', array(':listing' => $listings_id, ':cdn' => $cdn)), 'not-exist');
        }

        break;

    case '':
        throw new bException(tr('No method specified'), 'not-specified');

    default:
        throw new bException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown');
}
?>
