#!/usr/bin/php
<?php
/*
 * This is the chat management script
 */
$usage = './scripts/base/chat sync';

$help  = 'This is the chat management script



METHODS



sync                            - Syncs the core database user accounts with
                                  the chat database';

require_once(__DIR__.'/../../libs/startup.php');

cli_only();
load_libs('chat');

switch(cli_method()){
    case 'sync':
        log_console(tr('Syncing user accounts with chat database'), '', 'white');

        $users = sql_query('SELECT `id`, `name`, `username`, `email`, `status` FROM `users` WHERE `status` IS NULL');
        $chat  = sql_prepare('INSERT INTO `users` (`user_id`, `user_name`, `user_password`, `user_email`)
                              VALUES              (:user_id , :user_name , :user_password , :user_email )

                              ON DUPLICATE KEY UPDATE `user_name`  = :user_name,
                                                      `user_email` = :user_email', 'chat');
        $count = 0;

        log_console(tr('Updating ":count" user accounts', array(':count' => $users->rowCount())));

        while($user = sql_fetch($users)){
            cli_dot();

            $chat->execute(array(':user_id'       => $user['id'],
                                 ':user_password' => sha1(uniqid()),
                                 ':user_name'     => not_empty($user['username'], str_until($user['email'], '@').'-'.uniqid()),
                                 ':user_email'    => not_empty($user['email'], 'noemail')));
        }

        cli_dot(false);
        break;

    case '':
        throw new bException(tr('No method specified'), 'no-method');

    default:
        throw new bException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
}

log_console(tr('Done'), '', 'green');
?>
