#!/usr/bin/php
<?php
/*
 * This script can clear the contents of the tmp directory
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
    cli_no_arguments_left();
    log_console('Clearing configured tmp path ":tmp"', array(':tmp' => TMP), 'white');

    rename(TMP, $delete = unslash(TMP).'~delete');
    mkdir(TMP, $_CONFIG['fs']['dir_mode'], true);

    load_libs('file');
    file_delete_tree($delete);

    log_console(tr('Done!'), 'green');

}catch(Exception $e){
    throw new bException('scripts/base/cleartmp: Failed', $e);
}
?>
