#!/usr/bin/php
<?php
/*
 * Clear the BOM (Byte Order Mark) from all PHP files found in the specified tree.
 * Defaults to this project, unless another path was specified
 *
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @copyright Sven Oostenbrink <support@svenoostenbrink.com>
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');

if(!function_exists('clear_files')){
    function clear_files($path){
        try{
            if(!argument('quiet')){
                log_console('Checking path "'.str_log($path).'"');
            }

            $count = 0;

            foreach(scandir($path) as $file){
                if(($file == '.') or ($file == '..') or ($file == '.git')) continue;

                $file = slash($path).$file;

                if(is_dir($file)){
                    $count += clear_files($file);

                }else{
                    /*
                     * Only PHP files
                     */
                    if(substr($file, -4, 4) != '.php') continue;

                    $data = file_get_contents($file);

                    if(substr($data, 0, 3) == chr(0xEF).chr(0xBB).chr(0xBF)){
                        /*
                         * Found a twitcher! Gotta shootem in the head!
                         */
                        log_console('Found (and removed) BOM in file "'.str_log($file).'"', 'BOM found', 'yellow');

                        $count++;
                        $data = substr($data, 3);
                        file_put_contents($file, $data);
                    }
                }
            }

            return $count;

        }catch(Exception $e){
            throw new lsException('clearbom/clear_files(): Failed', $e);
        }
    }
}

try{
    $path = argument('path', true, ROOT);

    log_console('Searching "'.str_log($path).'" for PHP files with BOM signatures', 'clearbom', 'white');

    if(!file_exists($path)){
        throw new lsException('The specified path "'.str_log($path).'" does not exist', 'notexist');
    }

    $count = clear_files($path);

    log_console('Processed all files, found "'.str_log($count).'" files wtih BOM', 'finished', 'white');

}catch(Exception $e){
    throw new lsException('scripts/clearbom: Failed', $e);
}
?>
