#!/usr/bin/php
<?php
/*
 * This script is a front end to PHP composer
 */
$usage = "./scripts/base/composer OPTIONS\n".
         "./scripts/base/composer version\n";
         "./scripts/base/composer init\n";
         "./scripts/base/composer install\n";

$help  = "This is the help contents";

require_once(dirname(__FILE__).'/../../libs/startup.php');

load_libs('composer');

$composer = ROOT.'www/en/libs/external/composer.phar';

if(!file_exists($composer)){
    throw new bException(tr('composer.phar should be installed but was not found'), 'not-found');
}

switch(cli_method()){
    case 'init':
        /*
         * Setup a composer JSON data file
         */
        if(file_exists(ROOT.'composer.json')){
            if(!FORCE){
                throw new bException('Composer has already been initialized for this project', 'already-initialized');
            }
        }

        composer_init_file();
        break;

    case 'version':
        log_console(safe_exec('cd '.ROOT.'; php '.$composer.' -V'));
        break;

    case 'install':
        log_console(safe_exec('cd '.ROOT.'; php '.$composer.' install'));
        break;

    case 'require':
        log_console(safe_exec('cd '.ROOT.'; php '.$composer.' require'));
        break;

    case 'explain':
        $query = str_force(cli_arguments());
        log_console(safe_exec('cd '.ROOT.'; php '.$composer.' help '.$query));
        break;

    case 'list':
        log_console(safe_exec('cd '.ROOT.'; php '.$composer.' list'));
        break;

    case 'search':
        $query = str_force(cli_arguments());

        if(!$query){
            throw new bException(tr('No query specified'), 'not-specified');
        }

        log_console(safe_exec('cd '.ROOT.'; php '.$composer.' search '.$query));
        break;

    case 'show':
        $query = str_force(cli_arguments());

        if(!$query){
            throw new bException(tr('No query specified'), 'not-specified');
        }

        log_console(safe_exec('cd '.ROOT.'; php '.$composer.' show '.$query.' --all'));
        break;

    case '':
        throw new bException(tr('No method specified, please specify one of "init"'), 'no-method');

    default:
        throw new bException(tr('Unknown method ":method" specified, please specify one of "init"', array(':method' => cli_method())), 'unknown');
}
?>
