#!/usr/bin/php
<?php
/*
 * This script can compress CSS and JS files
 */
$usage = "./scripts/base/compress OPTIONS\n".
         "./scripts/base/compress [--all|--js|--css|--test /path/to/test/tree]\n";
         "./scripts/base/compress\n";

$help  = "This script can compress both CSS and JS files using the uglify-css and uglify-js Node-JS libraries

OPTIONS

--css                          -

--js                           -

--all                          -
";

require_once(__DIR__.'/../../libs/startup.php');

cli_only();
load_libs('uglify');

$js   = cli_argument('--js');
$all  = cli_argument('--all') or cli_argument('-a');
$css  = cli_argument('--css');

if(TEST){
    $path = arguments();
}

cli_no_arguments_left();

if(!$js and !$css){
    $all = true;
}

if(TEST){
    if(!$path){
        throw new bException('No test path specified.', 'not_specified');
    }

    log_console(tr('Running compression test'), 'white');
    uglify_js($path);
    log_console(tr('Finished compression test'), 'green');

}else{
    if($css or $all){
        log_console(tr('Compressing only CSS files'), 'white');
        uglify_css();
        log_console(tr('Finished compressing CSS files'), 'green');
    }

    if($js or $all){
        log_console(tr('Compressing only javascript files'), 'white');
        uglify_js();
        log_console(tr('Finished compressing javascript files'), 'green');
    }
}
?>
