#!/usr/bin/php
<?php
/*
 * This script can be used to test curl_get(0)
 */
$usage = "./scripts/base/curl\n".
         "./scripts/base/curl url URL [proxy] [useragent USERAGENT]\n";

$help  = "curl_get() interface script";

//$quiet = false;

require_once(dirname(__FILE__).'/../../libs/startup.php');

cli_only();
load_libs('curl');

$decode               = argument('--nodecode'  , false, true);
$params['url']        = argument('url'         , true);
$params['getheaders'] = argument('--getheaders', false, false);
$params['proxy']      = argument('proxy'       , false, $_CONFIG['curl']['proxy']);
$params['noproxy']    = argument('proxy'       , false, $_CONFIG['curl']['proxy']);
$params['proxies']    = argument('proxies'     , true , $_CONFIG['curl']['proxies']);
$params['useragent']  = argument('useragent'   , true , $_CONFIG['curl']['user_agents']);

if($params['proxies']){
	$params['proxies'] = array_force($params['proxies']);
}

if($params['noproxy']){
	$params['proxy'] = false;
}

if(!$params['url']){
	throw new bException(tr('Please specify a URL'), 'notspecfied');
}

$data = curl_get($params);

if(substr($data['data'], 0, 12) == 'PROXY_RESULT'){
	if($decode){
		$data         = json_decode(substr($data, 12));
		$data['data'] = base64_decode($data['data']);
	}
}

showdie($data);
?>
