#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
$usage = "./scripts/base/empty\n".
         "./scripts/base/empty option [option]\n";

$help  = "No help available";

//$quiet = false;

require_once(dirname(__FILE__).'/../../libs/startup.php');

cli_only();
load_libs('test');

foreach($argv as $arg){
	switch($arg){
		case 'all':
// :TODO: Implement
			break;
	}
}

test('emptyfunction()', 'Function call which should do blah blah', function(){
	try{
		if(emptyfunction('lkjerlkfwejf', 127)){
			throw new bException('Did not do blah blah');
		}

	}catch(Exception $e){
showdie($e);
	}
});

test_completed('empty()');


// Completed system tests
test_completed('empty', 'library');
?>
