#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
$usage = './scripts/base/empty
./scripts/base/empty option [option]';

$help  = 'No help available';

require_once(__DIR__.'/../../libs/startup.php');
cli_only();
load_libs('test');

switch(cli_method()){
    case '':
        throw new bException(tr('No method specified'), 'no-method');

    default:
        throw new bException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
}
?>
