#!/usr/bin/php
<?php
/*
 * This is the project permission fix script.
 *
 * All permissions will fall under these rules:
 *
 * All directories will be 0770, but have sticky bit set
 * All files will be 0660 permission
 * All script files (executables) will have 0770 permission
 *
 * All tree user and group will be set to $_CONFIG[deploy][user] $_CONFIG[deploy][group]
 *
 * @copyright Sven Oostenbrink <support@svenoostenbrink.com>
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
    /*
     * Load deployment configuration
     */
    include(dirname(__FILE__).'/../../config/deploy.php');

    log_console('Updating project file permissions...', 'deploy', 'white');

    $target        = argument('target', true, ENVIRONMENT);

    if(empty($_CONFIG['deploy'][$target])){
        throw new bException(tr('Selected environment "%env%" does not exist', array('%env%' => $target)), 'notexist');
    }

    $deploy_config = $_CONFIG['deploy'][$target];
    $target_dir    = argument('target_dir', true, $deploy_config['target_dir']);

    try{
        if(empty($_CONFIG['deploy'][$target])){
            throw new bException('Specified target environment "'.str_log($target).'" has no deploy configuration $_CONFIG[deploy]['.str_log($target).'] in "'.ROOT.'config/deploy.php"', 'missingconfiguration');
        }

        if(empty($deploy_config['user'])){
            throw new bException('No $_CONFIG[deploy]['.str_log($target).'][user] specified', 'missingconfiguration');
        }

        if(empty($deploy_config['group'])){
            throw new bException('No $_CONFIG[deploy]['.str_log($target).'][group] specified', 'missingconfiguration');
        }

        if(empty($deploy_config['dir_mode'])){
            throw new bException('No $_CONFIG[deploy]['.str_log($target).'][dir_mode] specified', 'missingconfiguration');
        }

        if(empty($deploy_config['file_mode'])){
            throw new bException('No $_CONFIG[deploy]['.str_log($target).'][file_mode] specified', 'missingconfiguration');
        }

        if(empty($deploy_config['www_mode'])){
            throw new bException('No $_CONFIG[deploy]['.str_log($target).'][www_mode] specified', 'missingconfiguration');
        }

    }catch(Exception $e){
        throw new bException('Check configuration in "'.ROOT.'config/deploy.php"', $e);
    }



    /*
     *
     */
    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' chown '.$deploy_config['user'].':'.$deploy_config['group'].' '.$target_dir.' -R;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update target directory tree user/group ownership', 'update_ownership');
    }

    log_console('Updated owner:group permissions', '', 'green');



    /*
     *
     */
    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' find '.$target_dir.' -type d -exec chmod '.$deploy_config['dir_mode'].' {} \;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update target directories mode', 'update_dirmode');
    }

    log_console('Updated directories mode...', '', 'green');



    /*
     *
     */
    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' find '.$target_dir.' -type f -exec chmod '.$deploy_config['file_mode'].' {} \;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update target files mode', 'update_dirmode');
    }

    log_console('Updated files mode...', '', 'green');



    /*
     *
     */
    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' find '.slash($target_dir).'scripts -type f -exec chmod 0750 {} \;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update script files mode', 'update_dirmode');
    }

    log_console('Updated script files mode...', '', 'green');



    /*
     * Update the file permissions of all paths in www
     */
    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' chmod '.$deploy_config['www_mode'].' '.slash($target_dir).'www/ -R', $exitcode);

    if($exitcode){
        throw new bException('Failed to set www path mode', 'update_dirmode');
    }

    log_console('Updated www path mode...', '', 'green');




    /*
     * Update the file permissions of temp directory
     */
    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' chmod ug+rwx,g+s,o-rwx '.slash($target_dir).'tmp/ -R', $exitcode);

    if($exitcode){
        throw new bException('Failed to set tmp path mode', 'update_dirmode');
    }

    log_console('Updated tmp path mode...', '', 'green');

    log_console('Finished updating www directories permissions...', 'filepermissions', 'green');

}catch(Exception $e){
    throw new bException('scripts/base/fix-permissions: Failed', $e);
}
?>
