#!/usr/bin/php
<?php
/*
 * This is the project permission fix script.
 *
 * All permissions will fall under these rules:
 *
 * All directories will be 0770, but have sticky bit set
 * All files will be 0660 permission
 * All script files (executables) will have 0770 permission
 *
 * All tree user and group will be set to $_CONFIG[deploy][user] $_CONFIG[deploy][group]
 *
 * @copyright Sven Oostenbrink <support@capmega.com>
 */
$usage = "./scripts/base/fix-permissions\n";

$help  = "The fix-permissions script will ensure that all files and directories have the configured file permissions, ensuring a safe site installation";

require_once(__DIR__.'/../../libs/startup.php');

/*
 * Load deployment configuration
 */
include(ROOT.'config/deploy.php');

$target = cli_argument('target', true, ENVIRONMENT);

cli_only(true);
cli_no_arguments_left();

load_libs('file');
log_console(tr('Updating project file permissions'), 'white');

if(empty($_CONFIG['deploy'][$target])){
    throw new bException(tr('Specified environment ":env" does not exist', array(':env' => $target)), 'not-exist');
}

$deploy_config = $_CONFIG['deploy'][$target];
$target_dir    = cli_argument('--target-dir', true, isset_get($deploy_config['target_dir'], ROOT));

try{
    if(empty($_CONFIG['deploy'][$target])){
        throw new bException(tr('Specified target environment ":target" has no deploy configuration $_CONFIG[deploy][:target] in ":ROOTconfig/deploy.php"', array(':target' => $target, ':ROOT' => ROOT)), 'missing-configuration');
    }

    if(!empty($deploy_config['target_server'])){
        if(empty($deploy_config['user'])){
            throw new bException(tr('No $_CONFIG[deploy][:target][user] specified', array(':target' => $target)), 'missing-configuration');
        }

        if(empty($deploy_config['group'])){
            throw new bException(tr('No $_CONFIG[deploy][:target][group] specified', array(':target' => $target)), 'missing-configuration');
        }

        if(!isset($deploy_config['modes'])){
            throw new bException(tr('No $_CONFIG[deploy][:target][modes] specified', array(':target' => $target)), 'missing-configuration');
        }
    }

    if(empty($deploy_config['sudo'])){
        /*
         * Don't use sudo at all
         */
        $sudo = '';

    }elseif(isset_get($deploy_config['sudo']) === true){
        /*
         * Use default sudo
         */
        $sudo = ' sudo ';

    }else{
        /*
         * Use configured sudo line
         */
        $sudo = ' '.$deploy_config['sudo'].' ';
    }

}catch(Exception $e){
    throw new bException(tr('Check configuration in ":ROOTconfig/deploy.php"', array(':ROOT' => ROOT)), $e);
}



/*
 * Update user:group only if we have a target server configuration, and if we're
 * using sudo, which is required for chown
 */
if($sudo and !empty($deploy_config['target_server'])){
    passthru($sudo.'chown '.$deploy_config['user'].':'.$deploy_config['group'].' '.ROOT.' -R;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update target directory tree user/group ownership', 'update-ownership');
    }

    log_console(tr('Updated owner:\group permissions to ":owner::group" for entire project', array(':owner' => $deploy_config['user'], ':group' => $deploy_config['group'])), 'green');
}



/*
 * Merge requested modes with default modes
 */
if(empty($deploy_config['target_server'])){
    /*
     * No target_server configuration specified, assume this is for local
     * development, make more writable
     */
    $default_modes = array('dirs'  => array('/'             => 'a-rwx,ug+rx,g+s',
                                            '/'             => 'ug+w'),

                           'files' => array('/'             => 'a-rwx,ug+r',
                                            '/'             => 'ug+w',
                                            '/scripts'      => 'ug+x'));

}else{
    $default_modes = array('dirs'  => array('/'                      => 'a-rwx,ug+rx,g+s',
                                            '/tmp'                   => 'ug+w',           // Should not be writable at all
                                            '/data'                  => 'ug+w',           // Should not be writable at all
                                            '/data/doc'              => 'ug-w',           // Should not be writable at all
                                            '/data/audio'            => 'ug-w',           // Should not be writable at all
                                            '/data/plugins'          => 'ug-w',           // Should not be writable at all
                                            '/www/en/pub/js/'        => 'ug+w',           // Required writable for bundler
                                            '/www/en/pub/css/'       => 'ug+w',           // Required writable for bundler
                                            '/www/en/admin/pub/js/'  => 'ug+w',           // Required writable for bundler
                                            '/www/en/admin/pub/css/' => 'ug+w'),          // Required writable for bundler

                           'files' => array('/'                      => 'a-rwx,ug+r',
                                            '/data'                  => 'ug+w',
                                            '/data/doc'              => 'ug-w',
                                            '/data/audio'            => 'ug-w',
                                            '/data/plugins'          => 'ug-w',
                                            '/www/en/pub/'           => 'ug+w',
                                            '/scripts'               => 'a-w,ug+x'));
}

if(empty($deploy_config['modes'])){
    $deploy_config['modes'] = array('dirs'  => array(),
                                    'files' => array());
}

foreach($default_modes as $type => $modes){
    $deploy_config['modes'][$type] = array_merge($deploy_config['modes'][$type], $default_modes[$type]);
}



/*
 * Apply all required file and directory modes
 */
foreach($deploy_config['modes'] as $type => $modes){
    switch($type){
        case 'dirs':
            foreach($modes as $path => $mode){
                /*
                 * Update modes for all directories in the specified path tree
                 *
                 * NOTE: The specified directory MAY not exist (eg. data/content)
                 * If this is the case, it is not a problem, just skip. This
                 * script should only care about that which exists
                 */
                if(VERBOSE){
                    log_console(tr('Updated directories mode for ":path"', array(':path' => $path)));
                }

                if(file_exists(unslash(ROOT).$path)){
                    passthru($sudo.'find '.unslash(ROOT).$path.' -type d -exec chmod '.$mode.' {} \;', $exitcode);

                    if($exitcode){
                        throw new bException(tr('Failed to update mode for directories in path ":path"', array(':path' => unslash(ROOT).$path)), 'failed');
                    }
                }
            }

            log_console(tr('Updated directories mode'), 'green');
            break;

        case 'files':
            foreach($modes as $path => $mode){
                /*
                 * Update modes for all files in the specified path tree
                 *
                 * NOTE: The specified directory MAY not exist (eg. data/content)
                 * If this is the case, it is not a problem, just skip. This
                 * script should only care about that which exists
                 */
                if(VERBOSE){
                    log_console(tr('Updated directories mode for ":path"', array(':path' => $path)));
                }

                if(file_exists(unslash(ROOT).$path)){
                    passthru($sudo.'find '.unslash(ROOT).$path.' -type f -exec chmod '.$mode.' {} \;', $exitcode);

                    if($exitcode){
                        throw new bException(tr('Failed to update mode for files in path ":path"', array(':path' => unslash(ROOT).$path)), 'failed');
                    }
                }
            }

            log_console(tr('Updated files mode'), 'green');
            break;

        default:
            throw new bException(tr('Unknown mode type ":type" specified', array(':type' => $type)), 'unknown');
    }
}

cli_run_once_local(true);
?>
