#!/usr/bin/php
<?php
/*
 * This is the project permission fix script.
 *
 * All permissions will fall under these rules:
 *
 * All directories will be 0770, but have sticky bit set
 * All files will be 0660 permission
 * All script files (executables) will have 0770 permission
 *
 * All tree user and group will be set to $_CONFIG[deploy][user] $_CONFIG[deploy][group]
 *
 * @copyright Sven Oostenbrink <support@svenoostenbrink.com>
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
    /*
     * Load deployment configuration
     */
    include(dirname(__FILE__).'/../../config/deploy.php');

    log_console('Updating project file permissions...', 'deploy', 'white');

    $target = argument('target', true, ENVIRONMENT);

    if(empty($_CONFIG['deploy'][$target])){
        throw new bException('Specified target environment "'.str_log($target).'" has no deploy configuration $_CONFIG[deploy]['.str_log($target).']', 'missingconfiguration');
    }

    $deploy_config = $_CONFIG['deploy'][$target];

    if(empty($deploy_config['user'])){
        throw new bException('No $_CONFIG[deploy]['.str_log($target).'][user] specified', 'missingconfiguration');
    }

    if(empty($deploy_config['group'])){
        throw new bException('No $_CONFIG[deploy][group] specified', 'missingconfiguration');
    }

    if(empty($deploy_config['dir_mode'])){
        throw new bException('No $_CONFIG[deploy][dir_mode] specified');
    }

    if(empty($deploy_config['file_mode'])){
        throw new bException('No $_CONFIG[deploy][file_mode] specified');
    }

    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' chown '.$deploy_config['user'].':'.$deploy_config['group'].' '.$deploy_config['target_dir'].' -R;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update target directory tree user/group ownership', 'update_ownership');
    }

    log_console('Updated owner:group permissions', '', 'green');

    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' find '.$deploy_config['target_dir'].' -type d -exec chmod '.$deploy_config['dir_mode'].' {} \;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update target directories mode', 'update_dirmode');
    }

    log_console('Updated directories mode...', '', 'green');

    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' find '.$deploy_config['target_dir'].' -type f -exec chmod '.$deploy_config['file_mode'].' {} \;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update target files mode', 'update_dirmode');
    }

    log_console('Updated files mode...', '', 'green');

    passthru((!empty($deploy_config['sudo']) ? ' sudo' : '').' find '.slash($deploy_config['target_dir']).'scripts -type f -exec chmod 0750 {} \;', $exitcode);

    if($exitcode){
        throw new bException('Failed to update script files mode', 'update_dirmode');
    }

    log_console('Updated script files mode...', '', 'green');

    log_console('Finished updating project file permissions...', 'filepermissions', 'green');

}catch(Exception $e){
    throw new bException('scripts/base/fixpermissions: Failed', $e);
}
?>
