#!/usr/bin/php
<?php
/*
 * This is the init script for the project. Run this script to ensure that the
 * database is running with the same version as the code
 *
 * Command line options:
 *
 * force                : Force a core database dump, and init from 0. This
 *                        option does NOT work on production environments
 *
 * dump                 : Dump the core database (this DOES work in production)
 *
 * fromprojectversion   : Make init fake the current project version registered
 *                        in the databaes to be the version number that follows
 *                        this option
 *
 * fromframeworkversion : Make init fake the current project version registered
 *                        in the databaes to be the version number that follows
 *                        this option
 *
 * @copyright Sven Oostenbrink <support@capmega.com>
 */
$usage = './scripts/base/init.
./scripts/base/init -F | --force
./scripts/base/init -d | --drop
./scripts/base/init -f | --frameworkversion VERSION
./scripts/base/init -p | --projectversion VERSION
./scripts/base/init -s | --section SECTION [-v VERSION]';

$help  = 'This script will initialize the database and system files to leave your data structures up to date with the current code version



ARGUMENTS



[-p VERSION]                    - Run init from project version VERSION
[--from-project-version VERSION]

[-f VERSION]                    - Run init from framework version VERSION
[--from-framework-version VERSION]

[--drop]                        - DROP, will drop the core database. Usually
                                  used on production systems in case the
                                  database needs to be dropped

[-F]                            - FORCE, will drop the core database and start
                                  init from version 0. NOTE: For safety against
                                  accidents, this will NOT work on production
                                  systems

-s | --section SECTION          - Initialize the specified section. This
                                  requires that ROOT/init/SECTION exists, and
                                  that a database connector called SECTION is
                                  configured. See $_CONFIG[db] or the
                                  `sql_connectors` database table for database
                                  connectors

-v | --section-version VERSION  - Only applies to section initialization. Will
                                  initialize the specified section starting at
                                  the specified VERSION';

require_once(__DIR__.'/../../libs/startup.php');

$drop                 = cli_argument('--drop');
$fromprojectversion   = not_empty(cli_argument('--from-project-version'  , true, null), cli_argument('-p', true, null));
$fromframeworkversion = not_empty(cli_argument('--from-framework-version', true, null), cli_argument('-f', true, null));
$section              = cli_argument('-s,--section', true);

cli_only(true);
load_libs('init');

if($section){
    /*
     * Section initialization
     */
    $version = cli_argument('-v,--section-version');
    cli_no_arguments_left();

    try{
        init_section($section, $version);

    }catch(Exception $e){
        if($e->getRealCode() == 'not-exist'){
            $e->makeWarning(true);
        }

        throw $e;
    }

}else{
    cli_no_arguments_left();

    try{

        if($drop){
            /*
             * Drop the core database
             */
            sql_init();
            if(is_object($core->sql['core']) and $core->sql['core'] instanceof PDO){
                $core->sql['core']->query('DROP DATABASE '.$_CONFIG['db']['core']['db']);

                log_console(tr('Dropped database ":db"', array(':db' => $_CONFIG['db']['core']['db'])), 'yellow');
                die();
            }
        }

        if($pfrom = $fromprojectversion){
            if(!str_is_version($pfrom)){
                throw new bException(tr('The specified fromprojectversion ":version" is not a valid version format. Please supply a version in format "n.n.n"', array(':version' => $pfrom)), 'warning/invalid');
            }
        }

        if($ffrom = $fromframeworkversion){
            if(!str_is_version($ffrom)){
                throw new bException(tr('The specified fromframeworkversion ":version" is not a valid version format. Please supply a version in format "n.n.n"', array(':version' => $ffrom)), 'warning/invalid');
            }
        }

        /*
         * During init, force EMULATE_PREPARES because loads of init stuff will NOT work without
         * Thanks PHP, for giving us the option between a shitty driver, or half a driver!
         */
        foreach($_CONFIG['db'] as $name => &$connector){
            if($name == 'default') continue;

            if(!empty($connector['init'])){
                $connector['pdo_attributes'] = array(PDO::ATTR_EMULATE_PREPARES  => true,
                                                     PDO::ATTR_STRINGIFY_FETCHES => true);
            }
        }

        init($pfrom, $ffrom);
        cli_run_once_local(true);

    }catch(Exception $e){
        if($e->getCode() != 'noinit'){
            throw new bException('scripts/base/init: Failed', $e);
        }

        log_console(tr('Core database init system has been disabled in db configuration'), 'yellow');
        throw $e;
    }
}
?>
