#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
$usage = './scripts/base/mysql method [OPTIONS]

./scripts/base/mysql list databases [OPTIONS]
./scripts/base/mysql list tables [OPTIONS]
./scripts/base/mysql list foreign-keys [OPTIONS]
./scripts/base/mysql change default-charset [OPTIONS]';

$help  = 'This script contains various methods to assist with various mysql operations



METHODS

list databases                   - List the available databases for the used
                                   connector

list tables                      - List the available tables for the used
                                   connector and database

list foreign-keys                - List the available foreign keys for the used
                                   connector and database





OPTIONS

--all                            - Apply to all databases

--databases                      - Apply to specified databases. NOTE: Specified
                                   databases will have to exist on the mysql
                                   server specified by the used connector!

--connector                      - Use a different database connector.
                                   By default, "core" is used, which will use
                                   connector $_CONFIG[db][core]

--database                       - Use a different database. By default, the
                                   first database found in the used connector
                                   will be used

replication

    list

        servers                  - List all currently registered servers

        databases                - List all currently registered databases

    add-master                   - Add new master

        --hostname HOSTNAME      - The hostname of the master server
                                  (e.g. s1.s.capmega.com)

        --database DATABASE      - The name of the database to replicate';

require_once(__DIR__.'/../../libs/startup.php');
load_libs('mysql');
cli_only();

$all       = cli_argument('--all');
$type      = cli_argument('-T', true, cli_argument('--type', true));
$connector = cli_argument('--connector', true);
$databases = cli_argument('--databases', 'all');

/*
 * Check required connector, load connector data
 */
if(!$connector){
    $connector = 'core';
}

if(empty($_CONFIG['db'][$connector])){
    throw new bException(tr('Specified connector ":connector" does not exist. Please check the configuration $_CONFIG[db][CONNECTORNAME]', array(':connector' => $connector)), 'not-exist');
}

$connector_data = $_CONFIG['db'][$connector];

/*
 * Check required database
 */
if($all){
    if($databases){
        throw new bException(tr('Both --databases and --all have been specified. Use either one or the other.'), 'invalid');
    }

    /*
     * Use all databases available on the server specified by this connector
     */
    $databases = sql_query('SELECT `TABLE_SCHEMA` FROM `information_schema`.`TABLES` GROUP BY `TABLE_SCHEMA`', null, null, $connector);

}else{
    if(!$databases){
        /*
         * Use the default database for the specified connector
         * If not, use the list of specified databases
         */
        $databases = array($_CONFIG['db'][$connector]['db']);
    }

    /*
     * Confirm that the required databases exist on the server specified by the connector
     */
    foreach($databases as $database){
        $exist = sql_get('SELECT `TABLE_SCHEMA` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = :TABLE_SCHEMA GROUP BY `TABLE_SCHEMA` LIMIT 1', 'TABLE_SCHEMA', array(':TABLE_SCHEMA' => $database), $connector);

        if(!$exist){
            throw new bException(tr('Specified database ":database" does not exist', array(':database' => $database)), 'not-exist');
        }
    }
}

/*
 * Process required methods
 */
switch(cli_method()){
    case 'import':
        switch(cli_method(1)){
            case 'timezones':
                try{
                    log_console(tr('Importing timezone data files in MySQL'), 'white');
                    log_console(tr('You may ignore any "Warning: Unable to load \'/usr/share/zoneinfo/........\' as time zone. Skipping it." messages'), 'warning');
                    log_console(tr('Please fill in MySQL root password in the following "Enter password:" request'), 'white');

                    safe_exec('mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -p  -u root mysql');

                }catch(bException $e){
                    /*
                     * Something went wrong during import Get MySQL error
                     */
                    $message = $e->getMessages();
                    $message = array_shift($message);
                    $message = json_decode_custom($message);
                    $message = array_shift($message);

                    if(strstr($message, 'ERROR 1045')){
                        throw new bException(tr('Incorrect MySQL root password supplied'), 'warning/passwordicorrect');
                    }

                    throw $e;
                }

                break;

            case '':
                throw new bException(tr('No sub method specified for method ":method"', array(':method' => cli_method())), 'not-specified');

            default:
                throw new bException(tr('Unknown sub method ":submethod" specified for method ":method"', array(':method' => cli_method(), ':submethod' => cli_method(1))), 'unknown-method');
        }

        break;

    case 'check':
        /*
         * Perform MySQL checks
         */
        switch(cli_method(1)){
            case 'timezone':
                // FALLTHROUGH
            case 'timezones':
                if(!$count = sql_get('SELECT COUNT(*) AS `count` FROM mysql.time_zone_name;')){
                    throw new bException('MySQL timezone tables are empty');
                }

                log_console($count, '', 'white');
                break;

            case '':
                throw new bException(tr('No sub method specified for method ":method"', array(':method' => cli_method())), 'not-specified');

            default:
                throw new bException(tr('Unknown sub method ":submethod" specified for method ":method"', array(':method' => cli_method(), ':submethod' => cli_method(1))), 'unknown-method');
        }

        break;

    case 'change':
        // FALLTHROUGH
    case 'alter':
        $type = cli_argument(1);

        switch($type){
            case 'charset':
                // FALLTHROUGH
            case 'default-charset':
                $tables     = cli_argument('--tables', 'all');
                $all_tables = cli_argument('--all-tables');
                $charset    = cli_argument(2);

                cli_no_arguments_left();

                if($tables and $all_tables){
                    throw new bException(tr('Both --all-tables and --tables have been specified. --all-tables is not needed, if --tables is not specified, all tables will be displayed'), 'invalid');
                }

                $tables = s_get_tables($tables, $databases);

                if($all){
                    log_console(tr('Changing default charset for tables (:count) for connector/host/database ":connector/:host/all databases"', array(':connector' => $connector, ':host' => $_CONFIG['db'][$connector]['host'], ':count' => $tables->rowCount())), 'white');

                }else{
                    log_console(tr('Changing default charset for tables (:count) in connector/host/database ":connector/:host/:database"', array(':connector' => $connector, ':host' => $_CONFIG['db'][$connector]['host'], ':database' => $database, ':count' => $tables->rowCount())), 'white');
                }

                log_console(str_size(tr('Database'), 40).tr('Table'), 'cyan');

                while($table = sql_fetch($tables)){
                    log_console(str_size($table['TABLE_SCHEMA'], 40).$table['TABLE_NAME']);
                    sql_query('ALTER TABLE `'.$table['TABLE_SCHEMA'].'`.`'.$table['TABLE_NAME'].'` CONVERT TO CHARACTER SET "'.$charset.'"', null, null, $connector);
                }
        }

        break;

    case 'list':
        $type = cli_argument(1);

        switch($type){
            case 'db':
                // FALLTHROUGH
            case 'dbs':
                // FALLTHROUGH
            case 'databases':
                cli_no_arguments_left();

                if(VERBOSE){
                    log_console(tr('Databases (:count) for connector/host ":connector/:host"', array(':connector' => $connector, ':host' => $_CONFIG['db'][$connector]['host'], ':count' => $databases->rowCount())), 'white');
                }

                log_console(tr('Database'), 'cyan');

                foreach($databases as $database){
                    log_console($database);
                }

                break;

            case 'tables':
                $tables     = cli_argument('--tables', 'all');
                $all_tables = cli_argument('--all-tables');

                cli_no_arguments_left();

                if($tables and $all_tables){
                    throw new bException(tr('Both --all-tables and --tables have been specified. --all-tables is not needed, if --tables is not specified, all tables will be displayed'), 'invalid');
                }

                $tables = s_get_tables($tables, $databases);

                if(VERBOSE){
                    if($all){
                        log_console(tr('Tables (:count) for connector/host/database ":connector/:host/all databases"', array(':connector' => $connector, ':host' => $_CONFIG['db'][$connector]['host'], ':count' => $tables->rowCount())), 'white');

                    }else{
                        log_console(tr('Tables (:count) for connector/host/database ":connector/:host/:database"', array(':connector' => $connector, ':host' => $_CONFIG['db'][$connector]['host'], ':database' => $database, ':count' => $tables->rowCount())), 'white');
                    }
                }

                log_console(str_size(tr('Database'), 40).tr('Table'), 'cyan');

                while($table = sql_fetch($tables)){
                    log_console(str_size($table['TABLE_SCHEMA'], 40).$table['TABLE_NAME']);
                }

                break;

            case 'fk':
                // FALLTHROUGH
            case 'foreign-key':
                // FALLTHROUGH
            case 'foreign-keys':
                $filter      = cli_argument('--filter'     , true);
                $reference   = cli_argument('--reference'  , true);
                $constraint  = cli_argument('--constraint' , true);
                $database    = cli_argument('--database'   , true);
                $foreign_key = cli_argument('--foreign-key', true, cli_argument('--fk', true));

                cli_no_arguments_left();

                $where       = ' WHERE `referenced_table_name` IS NOT NULL ';
                $execute     = array();

                if($foreign_key){
                    $having[] = ' `foreign_key` LIKE :foreign_key ';
                    $execute[':foreign_key'] = '%'.$foreign_key.'%';
                }

                if($database){
                    $having[] = ' `database` LIKE :database ';
                    $execute[':database'] = '%'.$database.'%';
                }

                if($constraint){
                    $having[] = ' `constraint` LIKE :constraint ';
                    $execute[':constraint'] = '%'.$constraint.'%';
                }

                if($reference){
                    $having[] = ' `references` LIKE :reference ';
                    $execute[':reference'] = '%'.$reference.'%';
                }

                $r = sql_query('SELECT `information_schema`.`key_column_usage`.`constraint_name`  AS `constraint`,
                                       `information_schema`.`key_column_usage`.`constraint_schema` AS `database`,
                                       CONCAT(`information_schema`.`key_column_usage`.`table_name`           , ".", `information_schema`.`key_column_usage`.`column_name`)            AS `foreign_key`,
                                       CONCAT(`information_schema`.`key_column_usage`.`referenced_table_name`, ".", `information_schema`.`key_column_usage`.`referenced_column_name`) AS `references`

                                FROM   `information_schema`.`key_column_usage` '.$where.(empty($having) ? '' : ' HAVING '.implode(' AND ', $having)), $execute);

                if($r->rowCount()){
                    log_console(tr('Listing ":count" foreign key references', array(':count' => $r->rowCount())), 'white');
                    log_console(tr('Database           Constraint name                          Foreign key                              References'), 'cyan');

                    while($row = sql_fetch($r)){
                        $row = str_size($row['database'], 18, ' ').' '.str_size($row['constraint'], 40, ' ').' '.str_size($row['foreign_key'], 40, ' ').' '.$row['references'];

                        if(!$filter or strstr($row, $filter)){
                            log_console($row);
                        }
                    }

                }else{
                    log_console(tr('No foreign key references found'), 'white');
                }

                break;

            case '':
                throw new bException(tr('No type specified, please use -T or --type'), 'not-specified');

            default:
                throw new bException(tr('Unknown type ":type" specified', array(':type' => $type)), 'unknown');
        }

        break;

    case 'replication':
        switch(cli_method(1)){
            case 'check':
                /*
                 * Get all databases
                 */
                log_console(tr('Checking databases replication status'), 'white');
                $databases = sql_query('SELECT    `databases`.`id`,
                                                  `databases`.`servers_id`,
                                                  `databases`.`status`,
                                                  `databases`.`replication_status`,
                                                  `databases`.`name` AS `database`,
                                                  `databases`.`error`,

                                                  `servers`.`id` AS `servers_id`,
                                                  `servers`.`hostname`,
                                                  `servers`.`ssh_port`,
                                                  `servers`.`replication_status` AS `servers_replication_status`,

                                                  `database_accounts`.`username`      AS `replication_db_user`,
                                                  `database_accounts`.`password`      AS `replication_db_password`,
                                                  `database_accounts`.`root_password` AS `root_db_password`

                                        FROM      `databases`

                                        LEFT JOIN `servers`
                                        ON        `servers`.`id`           = `databases`.`servers_id`

                                        LEFT JOIN `database_accounts`
                                        ON        `database_accounts`.`id` = `servers`.`database_accounts_id`

                                        WHERE     `databases`.`status` IS NULL');

                load_libs('ssh,servers');

                while($database = sql_fetch($databases)){
                    try{
                        /*
                         * Check if MySQL configuration still has this database
                         */
                        log_console(tr('Checking database :database from server :server', array(':database' => $database['database'], ':server' => $database['hostname'])), 'white');
                        $mysql_cnf_path = '/etc/mysql/mysql.conf.d/mysqld.cnf';
                        $mysql_cnf      = servers_exec($database['hostname'], 'test -f '.$mysql_cnf_path.' && echo "1" || echo "0"');

                        /*
                         * Mysql conf file does not exist
                         */
                        if(!$mysql_cnf[0]){
                            /*
                             * Try with other possible configuration file
                             */
                            $mysql_cnf_path = '/etc/mysql/my.cnf';
                            $mysql_cnf      = servers_exec($database['hostname'], 'test -f '.$mysql_cnf_path.' && echo "1" || echo "0"');

                            if(!$mysql_cnf[0]){
                                throw new bException(tr('MySQL configuration file :file does not exist on this server', array(':file' => $mysql_cnf_path)), 'not-exist');
                            }
                        }

                        $result = servers_exec($database['hostname'], 'grep -q -F \'binlog_do_db = '.$database['database'].'\' '.$mysql_cnf_path.' && echo "1" || echo "0"');

                        if(!$result[0]){
                            /*
                             * Database is not in binlog then it is disabled
                             */
                            mysql_update_database_replication_status($database, 'disabled');
                            continue;
                        }

                        /*
                         * Check channel for the server database
                         */
                        $result = sql_get('SHOW SLAVE STATUS FOR CHANNEL :channel', array(':channel' => $database['hostname']));

                        if(empty($result)){
                            /*
                             * No slave channel for this server
                             */
                            mysql_update_database_replication_status($database, 'disabled');
                            continue;
                        }

                        if(strtolower($result['Slave_IO_Running']) != 'yes' and strtolower($result['Slave_IO_Running']) != 'yes'){
                            ssh_mysql_slave_tunnel($database);
                            mysql_update_database_replication_status($database, 'error');
                            continue;
                        }

                        mysql_update_replication_status($database, 'enabled');

                    }catch(Exception $e){
                        log_console(tr('Error :error', array(':error' => $e)), 'red');
                    }
                }

                break;

            case 'list':
                switch(cli_method(2)){
                    case 'servers':
                        break;

                    case 'databases':
                        break;

                    case '':
                        throw new bException(tr('No sub method specified for the methods ":method0" ":method1"', array(':method0' => cli_method(), ':method1' => cli_method(1))), 'no-method');

                    default:
                        throw new bException(tr('Unknown sub method ":method2" specified for the methods ":method0" ":method1"', array(':method0' => cli_method(), ':method1' => cli_method(1), ':method2' => cli_method(2))), 'unknown-method');
                }

                break;

            case 'add-master':
                /*
                 * Get arguments and needed data
                 */
                $server                 = cli_arguments('--hostname,--database');
                $server['root_db_user'] = 'root';
                $server['arguments']    = '-q';
                cli_no_arguments_left();

                /*
                 * Setup master
                 */
                log_console(tr('Preparing master'), 'white');
                $master = mysql_master_replication_setup($server);

                /*
                 * Setup slave with master info
                 */
                log_console(tr('Preparing slave'), 'white');
                $slave = mysql_slave_replication_setup($master);
                break;

            case '':
                throw new bException(tr('No sub method specified for the method ":method"', array(':method' => cli_method())), 'no-method');

            default:
                throw new bException(tr('Unknown sub method ":submethod" specified for the method ":method"', array(':method' => cli_method(), ':submethod' => cli_method(1))), 'unknown-method');
        }

        break;

    case '':
        throw new bException(tr('No method specified'), 'not-specified');

    default:
        throw new bException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
}


/*
 *
 */
function s_get_tables($tables, $databases){
    global $all, $all_tables, $connector;

    try{
        if($all){
            /*
             * Show from all databases
             */
            if($tables){
                /*
                 * Show specified tables from all databases
                 */
                $tables = sql_in($tables);
                $tables = sql_query('SELECT CONCAT(`TABLE_SCHEMA`, `TABLE_NAME`) AS `id`, `TABLE_SCHEMA`, `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_NAME` IN ('.implode(',', array_keys($tables)).') GROUP BY `TABLE_NAME`', $tables, null, $connector);

            }else{
                /*
                 * Show all tables from all databases
                 */
                $tables = sql_query('SELECT CONCAT(`TABLE_SCHEMA`, `TABLE_NAME`) AS `id`, `TABLE_SCHEMA`, `TABLE_NAME` FROM `information_schema`.`TABLES` GROUP BY `TABLE_NAME`', null, null, $connector);
            }

        }else{
            /*
             * Show all tables from specified databases
             */
            $databases = sql_in($databases);
            $databases = sql_list('SELECT `TABLE_SCHEMA` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` IN ('.implode(',', array_keys($databases)).') GROUP BY `TABLE_SCHEMA` ORDER BY `TABLE_SCHEMA` ASC', $databases, null, $connector);
            $databases = sql_in($databases);

            if($tables){
                /*
                 * Show specified tables from specified databases
                 */
                $tables = sql_in($tables, ':table');
                $in     = array_merge($databases, $tables);
                $tables = sql_query(' SELECT CONCAT(`TABLE_SCHEMA`, `TABLE_NAME`) AS `id`, `TABLE_SCHEMA`, `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` IN ('.implode(',', array_keys($databases)).') AND `TABLE_NAME` IN ('.implode(',', array_keys($tables)).')  GROUP BY `TABLE_SCHEMA`, `TABLE_NAME` ORDER BY `TABLE_SCHEMA` ASC, `TABLE_NAME` ASC', $in, null, $connector);

            }else{
                /*
                 * Show specified tables from specified databases
                 */
                $tables = sql_query('SELECT CONCAT(`TABLE_SCHEMA`, `TABLE_NAME`) AS `id`, `TABLE_SCHEMA`, `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` IN ('.implode(',', array_keys($databases)).') GROUP BY `TABLE_SCHEMA`, `TABLE_NAME` ORDER BY `TABLE_SCHEMA` ASC, `TABLE_NAME` ASC', $databases, null, $connector);
            }
        }

        return $tables;

    }catch(Exception $e){
        throw new bException(tr('s_get_tables(): Failed'), $e);
    }
}
?>
