#!/usr/bin/php
<?php
/*
 * This is script can       be used to tesst the proxy system
 */
$usage = "./scripts/base/proxy
./scripts/base/proxy list
./scripts/base/proxy test URL
./scripts/base/proxy dump URL [ --proxy PROXY ]";

$help  = "This is a test script for the curl proxy interface

METHODS

list                            - List configured and available proxy servers

dump                            - Get data from the specified URL over a random
                                  proxy from the list of configured proxy
                                  servers

    --proxy                     - Use the specified proxy instead of a random
                                  proxy servers

test                            - Test all configured proxy machines";

require_once(dirname(__FILE__).'/../../libs/startup.php');
load_libs('curl');

switch(cli_method()){
    case 'list':
        cli_no_arguments_left();

        if(empty($_CONFIG['curl']['proxies'])){
            throw new bException(tr('No proxies have been configured, please check $_CONFIG[curl][proxies]'), 'not-configured');
        }

        foreach($_CONFIG['curl']['proxies'] as $proxy){
            cli_log($proxy);
        }

        break;

    case 'test':
        $errors  = 0;
        $url     = cli_argument(1);
        $proxies = cli_argument('--proxies', 'all');
        cli_no_arguments_left();

        if(!$url){
            throw new bException(tr('No url specified'), 'not-specified');
        }

        if(empty($proxies)){
            if(empty($_CONFIG['curl']['proxies'])){
                throw new bException(tr('No proxies have been configured, please check $_CONFIG[curl][proxies], or specify --proxies'), 'not-configured');
            }

            $proxies = $_CONFIG['curl']['proxies'];

        }else{
            $proxies = array_force($proxies);
        }

        foreach($proxies as $proxy){
            try{
                $data  = curl_get_proxy($url, null, $proxy);
                cli_log(tr('Proxy ":proxy" works correctly', array(':proxy' => $proxy)), 'green');

            }catch(Exception $e){
                $errors++;
                cli_log(tr('Proxy ":proxy" failed with ":e"', array(':proxy' => $proxy, ':e' => $e)), 'red');
            }
        }

        if($errors){
            cli_log(tr('Tested ":count" proxies, found ":errors" errors', array(':count' => count($proxies), ':errors' => $errors)), 'yellow');

        }else{
            cli_log(tr('Tested ":count" proxies, no errors found', array(':count' => count($proxies), ':errors' => $errors)), 'green');
        }

        break;

    case 'dump':
        $proxy = cli_argument('--proxy');
        $url   = cli_argument(0);
        cli_no_arguments_left();

        $data  = curl_get_proxy($url, null, $proxy);
        showdie($data['data']);

    case '':
        throw new bException(tr('No method specified'), 'not-specified');

    default:
        throw new bException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown');
}
?>
