#!/usr/bin/php
<?php
/*
 * This is script can       be used to tesst the proxy system
 */
$usage = "./scripts/base/proxy\n".
         "./scripts/base/proxy --url URL --proxy PROXY\n";

$help  = "This is a test script for the curl proxy interface";

require_once(dirname(__FILE__).'/../../libs/startup.php');

$url   = cli_argument('--url');
$proxy = cli_argument('--proxy');
cli_no_arguments_left();

load_libs('curl');

//$data = curl_get_proxy('http://test.com', null, 'http://localhost/toolkit/www/en/proxy.php?url=');

$data = curl_get_proxy($url, null, $proxy);

showdie($data['data']);
?>
