#!/usr/bin/php
<?php
/*
 * This is the servers management script.
 *
 * @auhthor Sven Olaf Oostenbrink <sven@capmega.com>
 * @copyright Copyright (c) 2018 Capmega
 * @license http://opensource.org/licenses/GPL-2.0 GNU Public License, Version 2
 * @category Function reference
 * @package base-scripts
 */
$usage = './scripts/servers
./scripts/servers add DOMAIN [DOMAIN DOMAIN ...] [--port PORT] [--register] [--account ACCOUNT]
./scripts/servers list servers [options]
./scripts/servers test [ssh|database|tunnel-database] [DOMAIN]
./scripts/servers show server SERVER
./scripts/servers test TEST SERVER';

$help  = 'This is the servers management script

This script can manage the servers. Servers must be registered in toolkit before
they can be managed.



METHODS



list [%DOMAIN%]                 - List all registerd servers, or by part of
                                  specified domain

        --only-domains          - Show only the domains. Useful with --quiet

        --provider SERVER       - List all servers for the specified provider

        --customer CUSTOMER     - List all servers for the specified customer


proxies
    insert  ROOT-DOMAIN         - Inserts a new server on the proxies chain
    NEW-DOMAIN LOCATION
    TARGET-DOMAIN
    [PROTOCOL[:PORT],
    PROTOCOL[:PORT]...]

    remove  ROOT-DOMAIN         - Removes a server from the proxies chain
    REMOVE-DOMAIN

show SERVER                     - Show details about the specified server

test TEST SERVER                - Execute the specified TEST on the specified
                                  SERVER. Available tests are: ssh, database,
                                  tunnel, database-tunnel

add DOMAIN [SSH-PORT]           - Add specified domain to the database

    --account | --ssh-account   - What SSH account to link to these servers. The
    [ACCOUNT]                     account can be specified by the accounts
                                  username, or the accounts id.

    --register                  - Automatically register the server fingerprints
                                  in the known_hosts file (NOT RECOMMENDED FOR
                                  SECURITY!)

update DOMAIN                   - Update specified domain in the database

delete ID | DOMAIN              - Set the status of the specified domain to
                                  "deleted" and remove the SSH fingerprints from
                                  both ssh_fingerprints and the
                                  ROOT/data/ssh/known_hosts file

erase ID | DOMAIN               - Erase the specified host from the database

register DOMAIN [SSH-PORT]      - Add the fingerprints for the specified
                                  domain / port to the ssh_fingerprints table
                                  and the ROOT/data/ssh/known_host file

unregister DOMAIN [SSH-PORT]    - Remove the registered domain / port
                                  fingerprints from the ROOT/data/ssh/known_host
                                  file and the ssh_fingerprints table';

require_once(__DIR__.'/../../libs/startup.php');

try{
    cli_only();
    load_libs('servers,ssh');

    switch(cli_method()){
        case 'add':
            $port      = not_empty(cli_argument('--port'), ssh_get_port());
            $register  = cli_argument('--register');
            $account   = cli_argument('--ssh-account,--account', true);
            $domains   = cli_arguments();
            $count     = 0;

            cli_no_arguments_left();

            if($account){
                $accounts_data = ssh_get_account($account);

                if(!$accounts_data){
                    throw new bException(tr('Specified account ":account" does not exist, try "servers list accounts"', array(':account' => $account)), 'warning/not-exist');
                }
            }

            if(!$domains){
                throw new bException(tr('No server(s) specified to add'), 'warning/not-specified');
            }

            foreach($domains as $domain){
                try{
                    servers_insert(array('domain'      => $domain,
                                         'port'        => $port,
                                         'register'    => $register,
                                         'ssh_account' => isset_get($accounts_data['seoname'])));

                    log_console(tr('Added server with domain ":domain"', array(':domain' => $domain)), 'green');
                    $count++;

                }catch(Exception $e){
                    if($e->getRealCode() !== 'validation'){
                        throw $e;
                    }

                    if(preg_match('/A server with domain ".+?" already exists/', $e->getMessage())){
                        log_console(tr('Server ":domain" already exists', array(':domain' => $domain)), 'warning');

                    }else{
                        log_console($e);
                    }
                }
            }

            if($count){
                log_console(tr('Added ":count" servers', array(':count' => $count)), 'success');

            }else{
                log_console(tr('Not added any servers'), 'warning');
            }

            break;

        case 'update':
            $server['domain'] = cli_argument(0);
            servers_update($server);
            break;

        case 'register':
            $domain = cli_argument(1);
            cli_no_arguments_left();

            $server = servers_like($domain);
            $server = servers_get($server);
            $count  = ssh_add_known_host($server['domain'], $server['port']);

            if($count){
                log_console(tr('Added ":count" domains', array(':count' => $count)), 'green');

            }else{
                log_console(tr('Added no domains, domain was probably already registered'), 'yellow');
            }

            break;

        case 'unregister':
            $domain = cli_argument(1);
            cli_no_arguments_left();

            $server = servers_like($domain);
            $server = servers_get($server);
            $count  = ssh_remove_known_host($server['domain'], $server['port']);

            if($count){
                log_console(tr('Removed ":count" domains', array(':count' => $count)), 'green');

            }else{
                log_console(tr('Removed no domains, domain was probably not registered'), 'yellow');
            }

            break;

        case 'delete':
            $status = ensure_variable($status, 'deleted');
            // FALLTHROUH

        case 'undelete':
            $status = ensure_variable($status, null);
            // FALLTHROUH

        case 'status':
            $domain = cli_argument(1);
            $status = ensure_variable($status, cli_argument(2));
            cli_no_arguments_left();

            $count = servers_unregister_host(array('domain'        => $domain,
                                                   'identity_file' => $identity_file));

            if($count){
                log_console(tr('Removed ":count" hashed domains', array(':count' => $count)), 'green');

            }else{
                log_console(tr('Removed no hashed domains, domain was probably not registered'), 'yellow');
            }

            break;

        case 'erase':
            $domain = cli_argument(1);
            cli_no_arguments_left();

            $count = servers_unregister_host(array('domain'        => $domain,
                                                   'identity_file' => $identity_file));

            if($count){
                log_console(tr('Removed ":count" hashed domains', array(':count' => $count)), 'green');

            }else{
                log_console(tr('Removed no hashed domains, domain was probably not registered'), 'yellow');
            }

            break;

        case 'list':
            $only_domains = cli_argument('--only-domains');
            $customer       = cli_argument('--customer', true);
            $provider       = cli_argument('--provider', true);
            $execute        = array();
            $where          = array();

            cli_no_arguments_left();

            if(DELETED){
                $where[] = ' `servers`.`status` = "deleted" ';

            }elseif(!ALL){
                $where[] = ' `servers`.`status` IS NULL OR `servers`.`status` = "testing" ';
            }

            if(STATUS){
                $execute = array_merge($execute, sql_in(ALL));
                $where[] = ' `servers`.`status` IN ('.implode(', ', array_keys(ALL)).') ';
            }

            if($customer){
                load_libs('customers');
                $customers_id = customers_get($customer, 'id');

                if(!$customers_id){
                    throw new bException(tr('The specified customer ":customer" does not exist', array(':customer' => $customer)), 'warning');
                }

                $execute[':customers_id'] = $customers_id;
                $where[] = ' `servers`.`customers_id` = :customers_id ';
            }

            if($provider){
                load_libs('providers');
                $providers_id = customers_get($provider, 'id');

                if(!$providers_id){
                    throw new bException(tr('The specified provider ":provider" does not exist', array(':provider' => $provider)), 'warning');
                }

                $execute[':providerss_id'] = $providers_id;
                $where[] = ' `servers`.`providerss_id` = :providerss_id ';
            }

            $query   = 'SELECT    `servers`.`id`,
                                  `servers`.`domain`,
                                  `servers`.`seodomain`,
                                  `servers`.`status`,
                                  `servers`.`createdon`,
                                  `servers`.`description`,

                                  `customers`.`name` AS `customer`,

                                  `providers`.`name` AS `provider`,

                                  `users`.`name`     AS `user_name`,
                                  `users`.`email`    AS `user_email`,
                                  `users`.`username` AS `user_username`,
                                  `users`.`nickname` AS `user_nickname`

                        FROM      `servers`

                        LEFT JOIN `customers`
                        ON        `customers`.`id` = `servers`.`customers_id`

                        LEFT JOIN `providers`
                        ON        `providers`.`id` = `servers`.`providers_id`

                        LEFT JOIN `users`
                        ON        `users`.`id` = `servers`.`createdby`';

            if(empty($where)){
                $where = '';

            }else{
                $where = ' WHERE '.implode(' AND ', $where);
            }

            $order   = ' ORDER BY `servers`.`status` IS NOT NULL DESC ';
            $servers = sql_query($query.$where.$order.(LIMIT ? ' LIMIT '.LIMIT : ''), $execute);

            if(!$servers->rowCount()){
                    log_console(tr('There are currently no servers registered'), 'QUIET/yellow');

            }else{
                if($only_domains){
                    log_console(tr('Hostname'), 'QUIET/cyan');

                    while($server = sql_fetch($servers)){
                        log_console($server['domain']);
                    }

                }else{
                    log_console(str_size(tr('#id'), 7).str_size(tr('Customer'), 25).str_size(tr('Provider'), 25).str_size(tr('Hostname'), 33).str_size(tr('Status'), 13).str_size(tr('Created by'), 32), 'QUIET/cyan');

                    while($server = sql_fetch($servers)){
                        log_console(str_size($server['id'], 6, ' ', true).' '.str_size($server['customer'], 24).' '.str_size($server['provider'], 24).' '.str_size($server['domain'], 32).' '.cli_status_color(str_size($server['status'], 12)).' '.name($server, 'user'));
                    }
                }
            }

            break;

        case 'proxies':
            switch(cli_method(1)){
                case 'insert':
                    load_libs('proxies');
                    $root_domain   = cli_argument(2);
                    $new_domain    = cli_argument(3);
                    $location      = cli_argument(4);
                    $target_domain = cli_argument(5);
                    $protocols     = cli_argument(6);

                    if(empty($root_domain)){
                        throw new bException(tr('No root domain specified'), 'warning/not-specified');
                    }

                    if(empty($new_domain)){
                        throw new bException(tr('No new domain specified'), 'warning/not-specified');
                    }

                    if(empty($location)){
                        throw new bException(tr('No location specified'), 'warning/not-specified');
                    }

                    if(empty($target_domain)){
                        throw new bException(tr('No target domain specified'), 'warning/not-specified');
                    }

                    log_console(tr('Inserting new server ":new" in chain for server ":root"', array(':new' => $new_domain, ':root' => $root_domain)), 'white');

                    try{
                        proxies_insert($root_domain, $new_domain, $target_domain, $location, $protocols);
                    }catch(Exception $e){
                        switch(str_from($e->getCode(), '/')){
                            case 'invalid':
                                $e->makeWarning(true);
                        }

                        throw $e;
                    }
                    break;

                case 'remove':
                    load_libs('proxies');

                    $root_domain   = cli_argument(2);
                    $remove_domain = cli_argument(3);

                    log_console('Removing host '.$remove_domain,'white');
                    proxies_remove($root_domain, $remove_domain);

                    break;

                case '':
                    throw new bException(tr('No sub method specified for method "proxies"'), 'no-method');

                default:
                    throw new bException(tr('Unknown sub method ":method" specified for method "proxies"', array(':method' => cli_method(1))), 'unknown-method');
            }

            break;

        case 'show':
            $server = cli_argument();
            $server = servers_like($server);
            $server = servers_get($server, true);

            if(empty($server['ssh_accounts_id'])){
                $server['allow_tcp_forward'] = 'N/A';

            }else{
                try{
                    load_libs('linux');
                    $server['allow_tcp_forward'] = linux_get_ssh_tcp_forwarding($server);

                }catch(Exception $e){
                    if($e->getRealCode() !== 'host-verification-missing'){
                        throw $e;
                    }

                    log_console(tr('Failed to get allow_tcp_forward information for host ":domain", it has no SSH key fingerprint in the known_hosts file.', array(':domain' => $server['domain'])), 'warning');
                }
            }

            $server  = array_hide($server);
            $domains = $server['domains'];

            unset($server['domains']);
            unset($domains[array_search($server['domain'], $domains)]);

            ksort($server);

            foreach($server as $key => $value){
                if($key == 'password') continue;
                log_console(cli_color($key.':', 'white').' '.json_encode_custom($value));
            }

            if($domains){
                foreach($domains as $key => $domain){
                    if($key){
                        log_console(cli_color('domain aliases: ', 'white').$domain);

                    }else{
                        log_console(str_repeat(18, ' ').$value);
                    }
                }

            }else{
                log_console(cli_color('domain aliases: ', 'white').'-');
            }

            break;

        case 'test':
            $test      = cli_argument(1);
            $requested = cli_argument(2);

            if(!$test){
                throw new bException(tr('No test specified. Please specify one of "ssh", "database", or "tunnel-database"'), 'warning/not-exist');
            }

            if(!$requested){
                throw new bException(tr('No server specified'), 'warning/not-exist');
            }

            try{
                $requested = servers_like($requested);
                $server    = servers_get($requested, true);

                switch($test){
                    case 'ssh':
                        if(!$server['ssh_accounts_id']){
                            throw new bException(tr('Skipped SSH access test for server ":server", the server does not have an SSH account assigned', array(':server' => $anchor)), 'warning');
                        }

                        servers_test($server['domain']);
                        log_console(tr('Finished SSH test succesfully for server ":server"', array(':server' => $server['domain'])), 'green');
                        break;

                    case 'database':
                        if(!$server['ssh_accounts_id'] or !$server['database_accounts_id']){
                            throw new bException(tr('Cannot test database access, server ":server", the server does not have a database account specified', array(':server' => $anchor)), 'warning/not-specified');
                        }

                        load_libs('mysql');
                        $results = mysql_exec($server['domain'], 'SELECT 1');

                        if((count($results) != 2) or ($results[end($results)] != 1)){
                            throw new bException($results, 'failed');
                        }

                        log_console(tr('Successfully tested database access for server ":server"', array(':server' => $server['domain'])), 'green');

                        break;

                    case 'tunnel-database':
                        if(!$server['ssh_accounts_id'] and !$server['database_accounts_id']){
                            throw new bException(tr('Skipped database over SSH tunnel access test for server ":server", the server does not have an SSH account or database account assigned', array(':server' => $anchor)), 'warning');
                        }

                        sql_test_tunnel($server);
                        log_console(tr('Successfully tested database access over SSH tunnel for server ":server"', array(':server' => $server['domain'])), 'green');
                        break;

                    default:
                        throw new bException(tr('Unknown test ":test" specified. Please specify one of "ssh", "database", or "tunnel-database".', array(':test' => $test)), 'warning/unknown');
                }

            }catch(Exception $e){
                switch($e->getCode()){
                    case 'host-verification-missing':
                        throw new bException(tr('SSH acces test failed for server ":server" because the host key verification showed this hosts key missing. Add the server to the known_hosts file first (currently only possible with executing "./scripts/base/ssh register :domain")', array(':server' => $anchor, ':domain' => $domain)), 'warning/failed');

                    case 'host-verification-failed':
                        throw new bException(tr('SSH acces test failed for server ":server" because the host key verification failed. Either somebody is trying to fake this server, or the server was reinstalled', array(':server' => $anchor, ':domain' => $domain)), 'failed');

                    case 'not-specified':
                        // FALLTHROUGH
                    case 'not-exist':
                        // FALLTHROUGH
                    case 'connect-failure':
                        // FALLTHROUGH
                    case 'dns-lookup-failure':
                        $e->makeWarning(true);
                }

                throw $e;
            }

            break;

        case '':
            throw new bException(tr('No method specified'), 'no-method');

        default:
            throw new bException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
    }

}catch(Exception $e){
    switch($e->getRealCode()){
        case 'not-exist':
            // FALLTHROUGH
        case 'multiple':
            // FALLTHROUGH
        case 'sudo':
            throw $e->makeWarning(true);
    }

    throw $e;
}
?>
