#!/usr/bin/php
<?php
/*
 * This is the Phoundation command line interface setup script
 */
$usage = './scripts/base/setup
./scripts/base/setup [-F | --force]';

$help  = 'This is the BASE framework install script. It will ask you a number of questions and from that setup and configure your BASE framework for your new project.';

require_once(__DIR__.'/../../libs/startup.php');
cli_only();

if(SEED){
    if(!FORCE){
        throw new bException(tr('This project has already been setup, and to avoid overwriting your previous setup, this script will be blocked unless you run it in FORCE mode using -F'), 'warning');
    }

    log_console(tr('WARNING! This project has already been setup! The setup script will run anyway because FORCE mode was specified on the command line'), 'warning');
}

log_console(tr('Welcome to the BASE framework setup script!'), 'white');
log_console(tr('You will be asked a number of questions about your project, needed to automatically setup your project. Afterwards, you can still change every setting in the config/ files'));



/*
 * Required for config/project.php setup
 */
$config['project']['seed'] = str_random(mt_rand(16, 32));
$fail                      = true;



/*
 * Get project name
 */
while($fail){
    $config['project']['project_name'] = cli_readline(tr('What is the name of your project?'), false, 'cyan');

    if(!preg_match('/[a-z-]{2,32}/i', $config['production']['project_name'])){
        log_console(tr('Please specify a valid project name. Valid project names can only contain "a-z-", must be lower case, and must be between 2 and 32 characters'), 'warning');
        continue;
    }

    break;
}



/*
 * Get project production domain
 */
while($fail){
    $config['production']['domain'] = cli_readline(tr('What is the production domain name (without http://, or https://)?'), false, 'cyan');

    if(!preg_match('/^(?!\-)(?:[a-zA-Z\d\-]{0,62}[a-zA-Z\d]\.){1,126}(?!\d+)[a-zA-Z\d]{1,63}$/', $config['production']['domain'])){
        log_console(tr('Please specify a valid domain name. It cannot surpass 255 characters, .'), 'warning');
        continue;
    }

    break;
}



/*
 * Get project production domain
 */
while($fail){
    $config['production']['multiple_sub_domains'] = cli_readline(tr('Will your project domain use multiple sub domains [N]?'), false, 'cyan');

    switch($config['production']['multiple_sub_domains']){
        case '':
            // FALLTRHOUGH
        case 'n':
            // FALLTRHOUGH
        case 'no':
            $config['production']['multiple_sub_domains'] = false;
            break;

        case 'y':
            // FALLTRHOUGH
        case 'yes':
            $config['production']['multiple_sub_domains'] = true;
            break;

        default:
            log_console(tr('Please specify y / yes or n / no.'), 'warning');
            continue;
    }

    break;
}



/*
 * Get project production domain
 */
if(!$config['production']['multiple_sub_domains']){
    while($fail){
        $config['production']['single_sub_domain'] = cli_readline(tr('Will your project domain use single sub domain? If no, just press enter, if yes, please specify the sub domain here'), false, 'cyan');

        if(!$config['production']['single_sub_domain']){
            $config['production']['single_sub_domain'] = '';

        }else{
            if(!preg_match('/[a-z-]{1,63}/i', $config['production']['db_core_user'])){
                log_console(tr('Please specify a valid domain sections. Valid domain sections can only contain "a-z-" and must be between 1 and 63 characters'), 'warning');
                continue;
            }
        }

        break;
    }
}



/*
 * Get project production database
 */
while($fail){
    $config['production']['db_core_db'] = cli_readline(tr('What is the production database name?'), false, 'cyan');

    if(!preg_match('/[0-9,a-z,A-Z$_]{2,16}/', $config['production']['db_core_db'])){
        log_console(tr('Please specify a valid database name. Valid database names can only contain "0-9,a-z,_" and must be between 2 and 16 characters'), 'warning');
        continue;
    }

    break;
}



/*
 * Get project production database
 */
while($fail){
    $config['production']['db_core_user'] = cli_readline(tr('What is the production database username?'), false, 'cyan');

    if(!preg_match('/[0-9,a-z,A-Z$_]{2,16}/', $config['production']['db_core_user'])){
        log_console(tr('Please specify a valid database name. Valid database usernames can only contain "a-z-" and must be between 2 and 16 characters'), 'warning');
        continue;
    }

    break;
}



/*
 * Get project production database
 */
while($fail){
    $config['production']['db_core_pass'] = cli_readline(tr('What is password to access your main database?'), false, 'cyan');
    break;
}



/*
 * Write project config/project.php file
 */
log_console(tr('Writing project file...'), 'white');
config_write_project();

unset($config['project']);



/*
 * Write project configuration files
 */
log_console(tr('Writing configuration files...'), 'white');

foreach($config as $file => $data){
    log_console(tr('Writing configuration file ":file"...', array(':file' => $file)));
    config_write($file, $data);
}
?>
