#!/usr/bin/php
<?php
/*
 * This is the SMS interface program
 */
$usage = "./scripts/base/sms send PHONE MESSAGE\n".
         "./scripts/base/sms send to PHONE [from PHONE] message MESSAGE [provider twilio|crmtext]\n";

         "./scripts/base/empty option [option]\n";

$help  = "This SMS script allows you to send out SMS messages using either twilio or crmtext as a provider, depending on the configuration";

require_once(dirname(__FILE__).'/../../libs/startup.php');

cli_only();
load_libs('sms,twilio');

switch(cli_method()){
    case 'send':
        if(!$to = cli_argument('to')){
            /*
             * Use sms phone message
             */
            $phone   = cli_argument(0);
            $message = str_force(cli_argument($phone, 'all'), ' ');

            if(!is_numeric(str_replace('+', '', $phone))){
                throw new bException(tr('Invalid arguments supplied. Please check script usage'), 'invalid');
            }

        }elseif(!$message = cli_argument('message')){
            throw new bException(tr('No message specified'), 'invalid');
        }

        sms_send_message($message, $phone);
        break;

    case 'getimages':
        log_console(tr('Downloading MMS images'), '', 'white');

        $r = sql_query('SELECT `sms_messages_id`,
                               `url`

                        FROM   `sms_images`

                        WHERE  `downloaded` IS NULL');

        while($image = sql_fetch($r)){
            twilio_download_image($image['sms_messages_id'], $image['url']);
            log_console(tr('Downloaded image ":image" for MMS message ":message"', array(':message' => $image['sms_messages_id'], ':image' => $image['url'])), '', 'green');
        }

        log_console(tr('Finished downloading all pending MMS images'), '', 'green');
        break;

    case '':
        throw new bException(tr('No method specified'), 'unknown');

    default:
        throw new bException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown');
}
?>
