#!/usr/bin/php
<?php
/*
 * This script will copy the target environments database and sync its files
 *
 * @copyright Sven Oostenbrink <support@ingiga.com>
 */
// :TODO: Add support to indicate sync other databases than the core database
$usage = "./scripts/base/sync ENVIRONMENT [OPTIONS]\n";

$help  = "The sync script can sync the target environment (for example production) database, images, etc. locally so that bug testing can be done with real data.

Possible arguments:

--no-init                      - Do not do execute a system init after the sync
                                 process has finished

--no-dump                      - Do not do the temporary mysql dump on the
                                 target environment

--no-clear                     - Do not clear local data content

--no-copy                      - Do not copy the temporary mysql dump on the
                                 target environment

--no-import                    - Do not import the temporary mysql dump from
                                 the target environment

--no-delete                    - Do not delete the temporary mysql dump from
                                 the target environment

--no-hook / --no-hooks         - Do not execute hooks

--no-files                     - Do not sync configured data directories

--no-functions                 - Do not sync mysql functions from the specified
                                 environment

--delete-sync / --sync-delete  - Delete data file paths before syncing (warning:
                                 This would cause rsync to redownload all files)

--no-cache-clear               - Do not clear cache after finishing the sync

--no-blog-update-url           - Do not update the blog page URL's

--no-badges-cached             - Do not clear badges_cached for badges

--no-blog-rebuild-post-urls    - Do not rebuild the blog post URLs after sync



HOOK SCRIPTS: Below are shown (in order) the hook scripts that will be executed
              If the hook scripts exist (in ROOT/scripts/hooks) they will be
              executed. If not, they will be ignored

sync_badges_cached";

$nologin = true;

require_once(dirname(__FILE__).'/../../libs/startup.php');

cli_only();
load_libs('init,array');



/*
 * Check command line parameters
 */
$environment     =  cli_argument(0);
$nodump          =  cli_argument('--no-dump');
$nocopy          =  cli_argument('--no-copy');
$nofiles         =  cli_argument('--no-files');
$noinit          =  cli_argument('--no-init');
$noclear         =  cli_argument('--no-clear');
$noimport        =  cli_argument('--no-import');
$nohooks         = (cli_argument('--no-hook') or cli_argument('--no-hooks'));
$nodelete        =  cli_argument('--no-delete');
$nodefinerfix    =  cli_argument('--no-definer-fix');
$nocacheclear    =  cli_argument('--no-cache-clear');
$nobadgescached  =  cli_argument('--no-badges-cached');
$noblogupdateurl =  cli_argument('--no-blog-rebuild-post-urls');
$deletesync      = (cli_argument('--delete-sync') or cli_argument('sync-delete'));

cli_no_arguments_left();



/*
 * Check environment
 */
if(empty($environment)){
    throw new bException(tr('No source environment specified, please use "-e ENVIRONMENT"'), 'not-specified');
}

if($environment == ENVIRONMENT){
    throw new bException(tr('Cannot sync from own environment ":env"', array(':env' => ENVIRONMENT)), 'same-environment');
}



/*
 * Get configuration for specified environment
 */
include(ROOT.'config/sync.php');



/*
 * Get configuration for specified environment
 */
$source_config = array_merge_complete(s_get_environment_configuration('production'), s_get_environment_configuration($environment));

if(!isset($source_config['deploy'][$environment])){
    throw new bException(tr('The specified environment ":env" does not exist', array(':env' => $environment)), 'not-exist');
}

$deploy_config = $source_config['deploy'][$environment];
$local_config  = s_get_environment_configuration(ENVIRONMENT);
$project       = strtolower(PROJECT);



/*
 * Environment exists?
 */
if(empty($deploy_config)){
    throw new bException(tr('The specified environment ":env" does not exist', array(':env' => $environment)), 'not-exist');
}



/*
 * SQL dump of source DB
 */
if($nodump){
    cli_log(tr('Skipping creating SQL dump file on remote server due to "--no-dump" command line parameters'), 'yellow');

}else{
    cli_log(tr('Creating SQL dump file on remote server'), 'white');
    passthru($command = 'ssh -p '.$deploy_config['target_port'].' -t '.($deploy_config['target_user'] ? $deploy_config['target_user'].'@' : '').$deploy_config['target_server'].' \''.($deploy_config['sudo'] ? ' sudo ' : '').'rm /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql* -f; '.($deploy_config['sudo'] ? ' sudo ' : '').'mysqldump --single-transaction -n -e '.(cli_argument('nofunctions') ? '' : '-R ').'--dump-date --no-autocommit --add-drop-database -u '.$source_config['db']['core']['user'].' -p'.escapeshellcmd($source_config['db']['core']['pass']).' -B '.$source_config['db']['core']['db'].' > /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql; '.($deploy_config['sudo'] ? ' sudo ' : '').'gzip -q /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql \'', $exitcode);

    if($exitcode){
        throw new bException(tr('Remote mysqldump failed with exit code ":code"', array(':code' => $exitcode)), 'remote');
    }
}



/*
 * SCP SQL dump to local server
 */
if($nocopy){
    cli_log(tr('Skipping copying remote SQL file locally due to "--no-copy" command line parameters'), 'yellow');

}else{
    cli_log(tr('Copying remote SQL file locally'), 'white');

    passthru('rm /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql.gz -f');
    passthru($command = 'scp -P '.$deploy_config['target_port'].' '.($deploy_config['target_user'] ? $deploy_config['target_user'].'@' : '').$deploy_config['target_server'].':/tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql.gz /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql.gz', $exitcode);

    if($exitcode){
        throw new bException(tr('Copy of remote mysqldump file to local server failed with exit code ":code"', array(':code' => $exitcode)), 'remote');
    }
}



/*
 * Import SQL file to local database
 */
if($noimport){
    cli_log(tr('Skipping importing remote SQL dump file in local MySQL server due to "--no-import" command line parameters'), 'yellow');

}else{
    /*
     * mysqldump always adds a "USE databasename" which is horrifyingly anoying, because the dump will be imported in the wrong database!
     * Remove it first!
     */
    cli_log(tr('Preparing remote SQL dump file ":file"', array(':file' => '/tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql')), 'white');
    passthru($command = 'cd /tmp/; rm /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql -f; gunzip /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql.gz', $exitcode);

    if($exitcode){
        throw new bException(tr('Gunzip of mysqldump file failed with exit code ":code"', array(':code' => $exitcode)), 'rsync');
    }

    cli_log(tr('Importing remote SQL dump file ":file" in local MySQL server', array(':file' => '/tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql')), 'white');
    passthru($command = 'cd /tmp/; sed -i -e"s/USE \`'.$source_config['db']['core']['db'].'\`;/USE \`'.$_CONFIG['db']['core']['db'].'\`;/" /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql', $exitcode);

    if($exitcode){
        throw new bException(tr('Rewrite of "USE DATABASENAME" in mysqldump file failed with exit code ":code"', array(':code' => $exitcode)), 'rsync');
    }

    $GLOBALS['sql_core'] = sql_connect($_CONFIG['db']['core'], false);

    sql_query('DROP   DATABASE IF EXISTS `'.$_CONFIG['db']['core']['db'].'`');
    sql_query('CREATE DATABASE `'.$_CONFIG['db']['core']['db'].'`');

    passthru($command = 'cat /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql | mysql -u '.$_CONFIG['db']['core']['user'].' -p"'.$_CONFIG['db']['core']['pass'].'" -B '.$_CONFIG['db']['core']['db'], $exitcode);

    if($exitcode){
        throw new bException(tr('MySQL import of mysqldump file failed with exit code ":code"', array(':code' => $exitcode)), 'mysql');
    }
}



/*
 * Remove temporary SQL dump file on source
 */
if($nodelete){
    cli_log(tr('NOT removing temporary remote SQL dump file from local and remote server due to "--no-delete" command line parameters'), 'yellow');

}else{
    cli_log(tr('Removing temporary remote SQL dump file from local and remote server'), 'white');

    passthru($command = 'ssh -p '.$deploy_config['target_port'].' -t '.($deploy_config['target_user'] ? $deploy_config['target_user'].'@' : '').$deploy_config['target_server'].' \''.($deploy_config['sudo'] ? ' sudo ' : '').'rm -f /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql*\'', $exitcode);

    if($exitcode){
        throw new bException(tr('Removal of temporary mysqldump file on remote server failed with exit code ":code"', array(':code' => $exitcode)), 'remote');
    }

    passthru($command = 'rm -f /tmp/'.$project.'_'.$source_config['db']['core']['db'].'.sql*', $exitcode);

    if($exitcode){
        throw new bException(tr('Removal of temporary mysqldump file on local server failed with exit code ":code"', array(':code' => $exitcode)), 'remote');
    }
}



/*
 * Clear local content data to avoid broken links and other possible problems,
 * just work with clean data from the target environment
 */
if($noclear){
    cli_log(tr('NOT clearing local content data due to "--no-clear" command line parameters'), 'yellow');

}else{
    cli_log(tr('Clearing local content data'), 'white');

    load_libs('file');
    file_delete_tree(ROOT.'data/content');
}



/*
 * Sync all
 */
if($nofiles){
    cli_log(tr('Skipping syncing remote paths with local server due to "--no-files" command line parameters'), 'yellow');

}else{
    cli_log(tr('Syncing remote paths with local server'), 'white');

    array_params($_CONFIG['sync']);

    if(!in_array('/data/content', $_CONFIG['sync']) and !in_array('/data/content/', $_CONFIG['sync'])){
        $_CONFIG['sync'][] = '/data/content/';
    }

    foreach($_CONFIG['sync'] as $path){
        if(!$path) continue;

        cli_log(tr('Syncing path ":path"', array(':path' => $path)), 'white');

        if($deletesync){
            cli_log(tr('Deleting local path ":path"', array(':path' => $path)), 'white');
            passthru($command = 'rm '.ROOT.$path.' -rf', $exitcode);

            if($exitcode){
                throw new bException(tr('Deleting of local path failed with exit code ":code"', array(':code' => $exitcode)), 'remote');
            }
        }

        try{
            passthru($command = 'rsync -aczvAXHS --progress -p '.($deploy_config['sudo'] ? '--rsync-path="sudo rsync" ' : '').'-e "ssh -p '.$deploy_config['target_port'].'" '.($deploy_config['target_user'] ? $deploy_config['target_user'].'@' : '').$deploy_config['target_server'].':'.slash($deploy_config['target_dir']).slash($path).' '.ROOT.slash($path).' --exclude="*.php" --exclude="*.css" --exclude="*.js" --exclude="/scripts/*" --exclude="/data/doc" --exclude="/data/system" --exclude="/data/mock*" --exclude="/data/sources" --exclude=".htaccess" --exclude=".git*" --exclude="/pub/*"', $exitcode);

        }catch(Exception $e){
            cli_log(tr('Failed to get path ":path" from environment ":environment"', array(':path' => $path, ':environment' => $environment)), 'yellow');
        }

        /*
         * Ensure write permissions to all files to avoid syn crashes on write protected files
         */
        safe_exec('chmod ug+w '.ROOT.' -R');

        if($exitcode){
            throw new bException(tr('Rsync of remote files with local server failed with exit code ":code"', array('code' => $exitcode)), 'rsync');
        }
    }
}



/*
 * Fix definer
 */
if($nodefinerfix){
    cli_log(tr('Skpping running definer fix due to "--no-definerfix" command line parameter'), 'yellow');

}else{
    cli_log(tr('Fixing function definers'));

    sql_query('UPDATE mysql.proc

               SET    definer = :new_definer

               WHERE  db      = :db
               AND    definer = :old_definer',

               array(':new_definer' => $local_config['db']['core']['user'].'@localhost',
                     ':old_definer' => $source_config['db']['core']['user'].'@localhost',
                     ':db'          => $local_config['db']['core']['db']));
}



/*
 *
 */
if($noinit){
    cli_log(tr('Skipping running init due to "--no-init" command line parameter'), 'yellow');

}else{
    /*
     * The init script wll check the database version, but that is very likely already read by now into a constant.
     * After a sync, the REAL current database version is very likely different and will have to be re-read. This can
     * only be done in a separate process, so dont execute the init with script_exec() but passthru() so that its
     * executed in a completely separate PHP process, while still dumping output on command line
     */
    cli_log(tr('Executing init script to ensure that database will be up to date'), 'white');
    passthru(ROOT.'scripts/base/init');

    if($exitcode){
        throw new bException(tr('Local init failed with exit code ":code"', array(':code' => $exitcode)), 'init');
    }
}



/*
 * Clear cache to avoid working with cache instead of newly synced data
 */
if(!$nocacheclear){
    load_libs('cache');
    cache_clear();
    cli_log(tr('Cleared cache'), 'green');
}



/*
 * Blog URL's will contain links that work for the specified environment,
 * but not the local environment, update them
 */
if($noinit or $noblogupdateurl){
    cli_log(tr('Skipping blog url update due to "--no-init" or "--no-blog-update-url" command line parameter'), 'yellow');

}else{
    load_libs('blogs');
// :DELETE: Sync script removes original DB, so theres a problem with PDO using that DB.
//    blogs_update_urls();
    passthru(ROOT.'scripts/base/blogs rebuild-post-urls');
}



/*
 * Clear badges_cached on users table
 */
if(!$nobadgescached){
    init_hook('sync_badges_cached', $nohooks);
}

cli_log(tr('Finished!'), 'green');



/*
 *
 */
function s_get_environment_configuration($environment){
    try{
        include(ROOT.'config/base/default.php');
        include(ROOT.'config/production.php');
        include(ROOT.'config/deploy.php');

        if($environment != 'production'){
            include(ROOT.'config/'.$environment.'.php');
        }

        /*
         * Optionally load the platform specific configuration file, if it exists
         */
        if(file_exists($file = ROOT.'config/'.$environment.'_'.PLATFORM.'.php')){
            include($file);
        }

        return $_CONFIG;

    }catch(Exception $e){
        throw new bException(tr('s_get_environment_configuration(): Failed'), $e);
    }
}
?>
