#!/usr/bin/php
<?php
/*
 *
 */
require_once(__DIR__.'/../../libs/startup.php');

try{
    if(cli_exclusive()){
        echo "This script is already running and it cannot run twice!\n";

    }else{
        while(true){
            echo "WHHEEE!! I got the world to my own!!\n";
            sleep(1);
        }
    }

}catch(Exception $e){
    throw new bException('scripts/test: Failed', $e);
}
?>
