#!/usr/bin/php
<?php
/*
 * This script can translate php code
 *
 * noutf / noutf8 / noutf8check  : Do not perform file content UTF8 checks
 *
 * Methods :
 *
 * translate                     : Generate the directories for each configured language
 *
 * clear                         : Delete all supported translations
 *
 * Options :
 *
 * -l --languages                : Specify the supported languages, otherwise
 *                                 $_CONFIG['language']['supported'] is used
 *
 * -m --mode                     : Specify the translation mode (strict, full, most or none)
 *
 * scan / scanonly / onlyscan    : Only perform translation scan, do not actually translate the files (NOT YET IMPLEMENTED)
 *
 * noupdate / nodb               : Do not send updated translations back to the translation server (NOT YET IMPLEMENTED)
 *
 * @copyright Sven Oostenbrink <support@ingiga.com>, Johan Geuze
 *
 * INFO:
 * If curl causes an exception due to an HTTP100 response
 * it is probably caused by Apache having issues with Expect headers
 * as it's explained in
 * http://stackoverflow.com/questions/3889574/apache-and-mod-proxy-not-handling-http-100-continue-from-client-http-417
 *
 * The solution is to add
 * <IfModule mod_headers.c>
 *    RequestHeader unset Expect early
 * </IfModule>
 * in the translation server apache configuration
 */
$usage = './scipts/base/translate clear
./scipts/base/translate scan
./scipts/base/translate translate';

$help = 'The translate script can translate the www/en directory to configured languages using the remote translation server

METHODS

clear                                   - Delete all www/LANGUAGE trees except
                                          www/en

scan                                    - Scan www/en for translatable strings
                                          and submit these strings to the
                                          translator

translate                               - Actually translate www/en to the
                                          configured target languages



OPTIONS

--ignore-php                            - Ignores translations that contain PHP
                                          code

--ignore-html                           - Ignores translations that contain
                                          HTML';

require_once(dirname(__FILE__).'/../../libs/startup.php');
load_libs('file,inet,curl,crypt');
load_config('translate');



$available_modes = array('strict',
                         'full',
                         'most',
                         'none');



/*
 *
 */
$languages = cli_argument('--languages', 'all');
$l         = cli_argument('-l', 'all');

if($l and $languages){
    throw new bException(tr('Both l- and --languages were specified. Please specify only one or the other'), 'invalid');
}

if($l){
    $languages = $l;
}



/*
 * Validate command line parameters
 */
if(empty($languages)){
    $languages = array_keys($_CONFIG['language']['supported']);

    if(empty($languages)){
        throw new bException(tr('No languages specified, no languages configured'), 'not-specified');
    }

    cli_log(tr('Translating to configured languages ":languages"', array(':languages' => implode(', ', $languages))), 'white');

}else{
    cli_log(tr('Translating to requested languages ":languages"', array(':languages' => implode(', ', $languages))), 'white');
}



/*
 * Process requested actions
 */
switch(cli_method()){
    case 'clear':
        cli_no_arguments_left();

        foreach($languages as $language){
            if($language == 'en'){
                continue;
            }

            cli_log(tr('Deleting ":language"', array(':language' => $language)));
            file_delete_tree(ROOT.'www/'.$language);
        }

        break;

    case 'scan':
        // fALLTHROUGH
    case 'translate':
        $ignore_php  = cli_argument('--ignore-php');
        $ignore_html = cli_argument('--ignore-html');
        $mode        = cli_argument('--mode', true, $_CONFIG['translate']['mode']);

        if(cli_method() == 'translate'){
            $noutf8check = (cli_argument('--no-utf') or cli_argument('--no-utf8')   or cli_argument('--no-utf8-check'));

            if(!in_array($mode, $available_modes)){
                throw new bException(tr('Unknown mode ":mode" specified', array(':mode' => $mode)), 'unknown');
            }

        }else{
            $noutf8check = (cli_argument('--no-utf') or cli_argument('--no-utf8')   or cli_argument('--no-utf8-check'));

            cli_log(tr('Scanning for translatable strings'), 'white');
        }

        cli_no_arguments_left();

        if($noutf8check){
            cli_log(tr('Skipping UTF8 check due to "noutf8check" command line parameter'), 'yellow');
        }

        foreach($languages as $id => $language){
            if(!preg_match('/\w{2}/', $language)){
                throw new bException(tr('Invalid language ":language" specified', array(':language' => $language)), 'invalid');
            }

            if($language == 'en'){
                unset($languages[$id]);
                cli_log(tr('Ignoring language "en - English"'), 'yellow');
            }
        }

        $results = array('translations' => array(),
                         'failed_html'  => array(),
                         'failed_php'   => array(),
                         'count'        => 0);

        file_tree_execute(array('path'      => ROOT.'www/en',
                                'recursive' => true,
                                'params'    => array('noutf8check' => $noutf8check),
                                'callback'  => function($file, $type, $params) use (&$results){

            global $_CONFIG;

            $extension = file_get_extension($file);

//            if(($extension != 'php') and ($extension != 'js')){
            if($extension != 'php'){
                /*
                 * Only translate PHP and JS files
                 */
                return;
            }

            if(VERBOSE){
                cli_log(tr('Scanning file ":file"', array(':file' => $file)));

            }else{
                cli_dot();
            }

            $content = file_get_contents($file);

            /*
             * UTF8 check!
             */
            if(!$params['noutf8check']){
                if(!str_is_utf8($content)){
                    /*
                     * Crap, this file is not UTF8 and will bork the translator. Update file contents, and safe file to force all files be UTF8
                     */
                    $content = utf8_encode($content);
                    file_put_contents($file, $content);

                    $forcedutf8[str_replace(ROOT, '', $file)] = true;

                    if(VERBOSE){
                        cli_dot();
                    }
                }
            }

//            preg_match_all('/tr\([\'"](.*?)[\'"](:?\s*,\s*array\((.*)\))?\)/iu', $content , $matches, PREG_PATTERN_ORDER);
            preg_match_all('/tr\([\'"](.*?)[\'"](:?\s*,\s*array\((.*)\))?\)/iu', $content , $matches, PREG_PATTERN_ORDER);

            if(!empty($matches[1])){
                foreach($matches[1] as $key => $value){
                    if(strip_tags($value, isset_get($_CONFIG['translate']['allowed_tags'])) != $value){
                        /*
                         * Translation string contains HTML!
                         */
                        $results['failed_html'][$value] = $file;
                        $results['count']++;

                    }elseif(strstr($value,'.$')){
                        /*
                         * Translation string contains PHP variables!
                         */
                        $results['failed_php'][$value] = $file;

                    }else{
                        /*
                         * Translation string is ok
                         */
                        $short_file = str_replace(ROOT, '', $file);
                        $results['translations'][$short_file][$value] = '';
                    }
                }
            }
        }));

        cli_dot(false);

        if(VERBOSE){
            cli_log(tr('Found :count strings', array(':count' => number_format($count))), 'white');
        }



        /*
         *
         */
        if(count($results['failed_html']) > 0){
            foreach($results['failed_html'] as $string => $file){
                if($ignore_html){
                    if(VERBOSE){
                        cli_log(tr('Ignoring file ":file" because of HTML', array(':file' => str_from($file, ROOT))), 'yellow');
                    }

                }else{
                    cli_log(tr('Found HTML ":html" in ":file"', array(':html' => str_size(str_truncate(str_log($string), 80), 80), ':file' => str_from($file, ROOT))), 'red');
                    $crash = true;
                }
            }

            if(!empty($crash)){
                throw new bException(tr('Translatable strings with disallowed HTML tags found'), 'translation-error');
            }

            cli_log(tr('Ignored ":count" files because of HTML', array(':count' => count($results['failed_html']))), 'yellow');
        }



        /*
         *
         */
        if(count($results['failed_php']) > 0){
            foreach($results['failed_php'] as $string => $file){
                if($ignore_php){
                    if(VERBOSE){
                        cli_log(tr('Ignoring file ":file" because of PHP', array(':file' => str_from($file, ROOT))), 'yellow');
                    }

                }else{
                    cli_log(tr('Found PHP ":php" in ":file"', array(':php' => $string, ':file' => $file)), 'red');
                    $crash = true;
                }
            }

            if(!empty($crash)){
                throw new bException(tr('Translatable strings with PHP code found'), 'translation-error');
            }

            cli_log(tr('Ignored ":count" files because of PHP', array(':count' => count($results['failed_php']))), 'yellow');
        }



        /*
         *
         */
        if(cli_method() == 'scan'){
            cli_log(tr('Sending translatable strings to server ":server"', array(':server' => $_CONFIG['translate']['url'])), 'green');

            /*
             * Construct data for sending
             */
            $data = array('project'      => PROJECT,
                          'api_key'      => $_CONFIG['translate']['api_key'],
                          'translations' => $results['translations'],
                          'method'       => 'post',
                          'options'         => array('mode' => $mode));

            try{
                $response = curl_get(array('url'         => $_CONFIG['translate']['url'],
                                           'getdata'     => true,
                                           'proxies'     => false,
                                           'getheaders'  => false,
                                           'post'        => array('data' => encrypt($data, $_CONFIG['translate']['passphrase'])),
                                           'httpheaders' => false));


//showdie($response);
            }catch(Exception $e){
                if(substr($e->getCode(), 0, 4) == 'HTTP'){
                    $server_message = $e->getData()['data'];
                    $code           = $e->getCode();

                    throw new bException(tr('Translation server gave HTTP code ":code" on URL ":url" with server message ":message"', array(':code' => $code, ':message' => $server_message, ':url' => $_CONFIG['translate']['url'])), 'translation_error');
                }

                throw new bException(tr('Error trying to connect with server : ":error"', array(':error' => $e->getMessage())), 'translation_error');
            }

            if(empty($response['status'])){
                throw new bException(tr('Error trying to connect with server'), 'translation_error');
            }

            $result = decrypt(trim($response['data']), $_CONFIG['translate']['passphrase']);
//showdie($result);

            if($result['status'] != 'success'){
                throw new bException(tr('Failed to send translatable strings'), $result['status'], $result);
            }

            cli_log('Sent translatable strings', 'green');
            die();
        }



        /*
         * Translate to specified languages
         */
        foreach($languages as $language){
            $source_dir = ROOT.'www/en';
            $target_dir = ROOT.'www/'.$language;

            cli_log(tr('Translating language ":language"', array(':language' => $language)), 'white');
            cli_log(tr('Requesting translations from server url":url"', array(':url' => $_CONFIG['translate']['url'])));

            /*
             * Construct data for sending
             */
            $data = array('project'         => PROJECT,
                          'api_key'         => $_CONFIG['translate']['api_key'],
                          'translations'    => $results['translations'],
                          'target_language' => $language,
                          'method'          => 'get',
                          'options'         => array('mode' => $mode));

            try{
                $response = curl_get(array('url'         => $_CONFIG['translate']['url'],
                                           'getdata'     => true,
                                           'proxies'     => false,
                                           'getheaders'  => false,
                                           'post'        => array('data' => encrypt($data, $_CONFIG['translate']['passphrase'])),
                                           'httpheaders' => false));
//showdie($response);
            }catch(Exception $e){
//show($e);
                if(substr($e->getCode(), 0, 4) == 'HTTP'){
                    $server_message = $e->getData()['data'];
                    $code           = $e->getCode();

                    throw new bException(tr('Translation server gave HTTP code ":code" on URL ":url" with server message ":message"', array(':code' => $code, ':message' => $server_message, ':url' => $_CONFIG['translate']['url'])), 'translation_error');
                }

                throw new bException(tr('Error trying to connect with server : ":error"', array(':error' => $e->getMessage())), 'translation_error');
            }

            if(empty($response['status'])){
                throw new bException(tr('Error trying to connect with server'), 'translation_error');
            }

            $returned_data = decrypt(trim($response['data']), $_CONFIG['translate']['passphrase']);

            if(!is_array($returned_data) or (isset_get($returned_data['status']) != 'success') or (!is_array(isset_get($returned_data['translations'])))){
                throw new bException(tr('Failed to receive translations', 'error'));
            }

            $count = 0;

            foreach($returned_data['translations'] as $translations){
                $count += count($translations);
            }

            cli_log(tr('Received ":count" translations for ":files" files from translation server', array(':count' => $count, ':files' => count($returned_data['translations']))), 'green');



            /*
             * Translations ready, start processing.
             * Delete target dir
             */
            try{
                // if(VERBOSE){
                //     cli_log('Deleting target dir '.$target_dir, 'translate', '', true);
                // }

                shell_exec('rm -rf '.$target_dir);

                // Copy english to target dir
                cli_log(tr('Copying ":source" to ":target"', array(':source' => $source_dir, ':target' => $target_dir)));
                shell_exec('cp -a '.$source_dir.' '.$target_dir);

                // :DELETE: Its not going to save too much space, and doesnt make sense
                //          to only link css and forgot about js, images, etc
                // // CSS should be symlink since it wont change between languages
                // file_delete_tree(slash($target_dir).'pub/css');
                // symlink('../../en/pub/css', slash($target_dir).'pub/css');

                cli_log(tr('Applying translations'), '', true);

                foreach($returned_data['translations'] as $short_file => $data){
                    if(VERBOSE){
                        cli_log(tr('Translating ":file"', array(':file' => $short_file)), '', false);

                    }else{
                        cli_dot();
                    }

                    if(!empty($forcedutf8[$short_file])){
                        if(VERBOSE){
                            cli_log(tr('*FORCED-UTF8* '), 'yellow', false);
                        }
                    }

                    if(!file_exists(ROOT.$short_file)){
                        cli_log(tr(' File ":file" not found', array(':file' => ROOT.$short_file)), 'red');

                    }else{
                        //store new file
                        $filedata    = file_get_contents(ROOT.$short_file);
                        $target_file = str_replace($source_dir, $target_dir, ROOT.$short_file);

                        //replace strings
                        foreach($data as $source => $translation){
                            if(VERBOSE){
                                cli_dot();
                            }

                            $from     = array('tr("'.$source.'"'     , "tr('".$source."'");
                            $to       = array('tr("'.$translation.'"', "tr('".$translation."'");
                            $filedata = str_replace($from, $to, $filedata);
                        }

                        file_put_contents($target_file, $filedata);

                        if(VERBOSE){
                            cli_log('Saved', 'green');
                        }
                    }
                }

                cli_dot(false);

                if($returned_data['stats']['translations_missing'] > 0){
                    cli_log(tr('Missing ":count" translations', array(':count' => number_format($returned_data['stats']['translations_missing']))), 'yellow');
                }

                cli_log(tr('Successfully translated ":count" sections', array(':count' => number_format($returned_data['stats']['translations_done']))), 'green');

            }catch(Exception $e){
                throw new bException(tr('Error applying ":lang" translations', array(':lang' => $language)), $e);
            }
        }

        break;

    case '':
        throw new bException(tr('No method specified, please specify one of "clear", "scan", or "translate"'), 'no-method');

    default:
        throw new bException(tr('Unknown method ":method" specified, please specify one of "clear", "scan", or "translate"', array(':method' => cli_method())), 'unknown');
}
?>
