#!/usr/bin/php
<?php
/*
 * This is an empty test script template
 */
$usage = "./scripts/base/update [local]\n".
         "./scripts/base/update\n";

$help  = "The deploy script can pull all the latest BASE updates from either a local BASE repository, or the central main BASE repository";

require_once(dirname(__FILE__).'/../../libs/startup.php');

try{
    if(argument('local')){
        /*
         * Get the data from the local base repository instead of the centralized one
         */
        $base_server    = 'localhost';
        $base_directory = '/home/'.getenv('USER').'/projects/base';

        log_screen('scripts/update: Running in "local" mode, getting all base data from "'.$base_directory.'" for faster update', 'deploy/test', 'yellow');

    }else{
        $base_directory = '/var/www/projects/base';
        $base_server    = $_CONFIG['system']['updater'];
    }

    $branch = argument('branch', true, 'production');

    if(!$branch){
        throw new lsException('No branch specified', 'nobranch');
    }

    if(TEST){
        log_screen('scripts/update: Running update script in test mode, NOT REALLY UPDATING!', 'deploy/test', 'yellow');
    }

    if(FORCE){
        log_screen('scripts/update: Running update script in forced mode, WILL UPDATE EVEN IF GIT CHANGES AND / OR MINOR PROBLEMS ARE FOUND!', 'deploy/force', 'yellow');
    }

    // Ensure we are at the root of the project within this context, or git will fail!
    chdir(ROOT);

    // Check if we are not on main base repository
    if(trim(shell_exec('grep "/git/base.git" '.ROOT.'.git/config'))) {
        throw new lsException('Cannot be run on main base repository', 'WRONGREPOS');
    }

    // Check if we dont have any commits
    if(!trim(shell_exec('git status | grep "nothing to commit" | wc -l')) AND !FORCE) {
        throw new lsException('Git commit pending', 'COMMITFIRST');
    }

    //update libraries from base
    if(argument('local')){
        log_console('Skipping base branch update due to local mode', 'update', 'yellow');

    }else{
        log_console('Updating from base branch "'.$branch.'"', 'update', 'white');
        echo shell_exec('ssh -t '.$base_server.' "cd '.$base_directory.'; git reset --hard; git checkout '.$branch.'; git pull origin '.$branch.'"');
    }

    //copy from base
    log_console('Copying from base', 'update', 'white');

    if(empty($test)){
        // Libraries
        log_console('Libs', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms '.$base_server.':'.$base_directory.'/www/en/libs '.ROOT.'www/en/');
        echo shell_exec('rsync -av --no-perms '.$base_server.':'.$base_directory.'/www/en/tests '.ROOT.'www/en/');

        // Base AJAX files
        log_console('Ajax', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms '.$base_server.':'.$base_directory.'/www/en/ajax/base '.ROOT.'www/en/ajax/');

        // Scripts
        log_console('Scripts', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms --delete '.$base_server.':'.$base_directory.'/scripts/base/* '.ROOT.'scripts/base/');
        echo shell_exec('rsync -av --no-perms --delete '.$base_server.':'.$base_directory.'/scripts/tests/* '.ROOT.'scripts/base/');

        // Framework init files
        log_console('Framework updates', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms --delete '.$base_server.':'.$base_directory.'/init/framework/* '.ROOT.'init/framework/');

        // Base configuration
        log_console('Config', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms --delete '.$base_server.':'.$base_directory.'/config/base/* '.ROOT.'config/base/');

        // Javascript
        log_console('Javascript', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms --delete '.$base_server.':'.$base_directory.'/www/en/pub/js/base/* '.ROOT.'www/en/pub/js/base/');

        // CSS
        log_console('Stylesheets', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms --delete '.$base_server.':'.$base_directory.'/www/en/pub/css/base/* '.ROOT.'www/en/pub/css/base/');

        // Images
        log_console('Images', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms --delete '.$base_server.':'.$base_directory.'/www/en/pub/img/base/* '.ROOT.'www/en/pub/img/base/');

        // Documentation
        log_console('Documentation', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms '.$base_server.':'.$base_directory.'/data/doc/* '.ROOT.'data/doc/');

        // Sources
        log_console('Data sources', 'copy', 'purple');
        echo shell_exec('rsync -av --no-perms '.$base_server.':'.$base_directory.'/data/sources/* '.ROOT.'data/sources/');
    }

    //execute init script
    log_console('Excuting init script', 'update', 'white');
    echo shell_exec('cd '.ROOT.'scripts/base/;export '.PROJECT.'_ENVIRONMENT='.ENVIRONMENT.'; php init');

    //Done
    log_console('Commit updates', 'update', 'white');
    echo shell_exec('cd '.ROOT.';git add .;git commit -am "Update from base"');

    log_console('Done', 'update', 'white');

}catch(Exception $e){
    cli_error('scripts/base/update: Failed', $e);
}
?>
