#!/usr/bin/php
<?php
/*
 * This script will display version information
 */
$usage = "./scripts/base/version\n".
         "./scripts/base/version [php|serialize|serialized]\n";

$help  = "The version script will supply you with version information about this copy of the base framework";

require_once(dirname(__FILE__).'/../../libs/startup.php');

switch(cli_method()){
    case 'php':
        //FALLTHROUGH
    case 'serialize':
        //FALLTHROUGH
    case 'serialized':
        die(serialize(array('name'      => PROJECT,
                            'framework' => FRAMEWORKCODEVERSION,
                            'project'   => PROJECTCODEVERSION)));

    case '':
        log_console(tr('BASE project ":project" with framework version ":fversion" and project version ":pversion"', array(':project' => PROJECT, ':fversion' => FRAMEWORKCODEVERSION, ':pversion' => PROJECTCODEVERSION)), 'white');
        break;

    default:
        throw new bException(tr('Unknown method ":method" specified', array(':method' => cli_method())), 'unknown-method');
}

?>
