#!/usr/bin/php
<?php
/*
 * This script will display version information
 */
$usage = "./scripts/base/version\n".
         "./scripts/base/version php|serialize|serialized\n";

$help  = "The version script will supply you with version information about this copy of the base framework";

require_once(dirname(__FILE__).'/../../libs/startup.php');

foreach($argv as $arg){
    switch(strtolower($arg)){
        case 'php':
            //FALLTHROUGH
        case 'serialize':
            //FALLTHROUGH
        case 'serialized':
            die(serialize(array('framework' => FRAMEWORKCODEVERSION,
                                'project'   => PROJECTCODEVERSION)));
    }
}

die('framework: '.FRAMEWORKCODEVERSION.' project: '.PROJECTCODEVERSION."\n");
?>
