#!/usr/bin/php
<?php
/*
 * This script can create new mailings
 */
$quiet = true;
require_once(__DIR__.'/../../../libs/startup.php');

try{
    cli_only();
    cli_exclusive();

    $params['name']       = not_empty(cli_argument('name'     , true), cli_argument('title'        , true));
    $params['content']    = not_empty(cli_argument('content'  , true), cli_argument('content_file' , true));
    $params['from']       = not_empty(cli_argument('from'     , true), cli_argument('replace_from' , true));
    $params['to']         = not_empty(cli_argument('to'       , true), cli_argument('replace_to'   , true));
    $params['from_name']  = not_empty(cli_argument('fromname' , true), cli_argument('from_name'    , true));
    $params['from_email'] = not_empty(cli_argument('fromemail', true), cli_argument('from_email'   , true));

    $params['subject']    = cli_argument('subject', true);
    $params['starton']    = cli_argument('starton', true, null);
    $params['users']      = cli_argument('users'  , true);

    $params['status']     = (cli_argument('start') ? 'started' : null);

    load_libs('mailer');
    mailer_insert($params);

    log_console('Created mailer "'.$params['name'].'"', 'info', 'white');

}catch(Exception $e){
    throw new bException('scripts/mailer/create: Failed', $e);
}
?>
