#!/usr/bin/php
<?php
/*
 * This script can delete specified or all mailings
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../../libs/startup.php');


try{
    cli_only();
    this_script_already_runs();

    load_libs('mailer');

    if($count = mailer_delete($argv)){
        log_console('Deleted "'.$count.'" mailers', '', 'white');

    }else{
        log_console('No mailers deleted', '', 'yellow');
    }

}catch(Exception $e){
    throw new ('scripts/mailer/delete: Failed', $e);
}
?>
