#!/usr/bin/php
<?php
/*
 * This script can delete specified or all mailings
 */
$quiet = true;
require_once(__DIR__.'/../../../libs/startup.php');


try{
    cli_only();
    cli_exclusive();

    load_libs('mailer');

    if($count = mailer_delete($argv)){
        log_console('Deleted "'.$count.'" mailers', '', 'white');

    }else{
        log_console('No mailers deleted', '', 'yellow');
    }

}catch(Exception $e){
    throw new bException('scripts/mailer/delete: Failed', $e);
}
?>
