#!/usr/bin/php
<?php
/*
 * This script will try to send mails from all mailers that have been set to "running"
 */
$quiet = true;
require_once(dirname(__FILE__).'/../../../libs/startup.php');

try{
    cli_only();
    cli_exclusive();

    $wait  = cli_argument('wait' , true);
    $count = cli_argument('count', true);
    $test  = not_empty(cli_argument('test', true), cli_argument('debug', true));

    load_libs('mailer');
    if($count = mailer_send($count, $wait, $test)){
        log_console('Sent "'.$count.'" mails', '', 'white');

    }else{
        log_console('No mails sent', '', 'yellow');
    }

}catch(Exception $e){
    throw new bException('scripts/mailer/send: Failed', $e);
}
?>
