#!/usr/bin/php
<?php
/*
 * This script can start specified or all mailings
 */
$quiet = true;
require_once(__DIR__.'/../../../libs/startup.php');


try{
    cli_only();
    cli_exclusive();

    load_libs('mailer');

    if(cli_argument('auto')){
        $count = mailer_start('auto');

    }elseif(cli_argument('all')){
        $count = mailer_start('all');

    }else{
        $mailers = cli_argument('mailers', true, cli_argument('mailer', true, cli_argument('mailings', true)));
        $count   = mailer_start($mailers);
    }

    if($count){
        log_console('Started "'.$count.'" mailers', '', 'white');

    }else{
        log_console('No mailers started', '', 'yellow');
    }

}catch(Exception $e){
    throw new bException('scripts/mailer/start: Failed', $e);
}
?>
