#!/usr/bin/php
<?php
/*
 * This script can stop specified or all mailings
 */
$quiet = true;
require_once(__DIR__.'/../../../libs/startup.php');


try{
    cli_only();
    cli_exclusive();

    load_libs('mailer');

    if($count = mailer_stop($argv)){
        log_console('Stopped "'.$count.'" mailers', '', 'white');

    }else{
        log_console('No mailers stopped', '', 'yellow');
    }

}catch(Exception $e){
    throw new bException('scripts/mailer/stop: Failed', $e);
}
?>
