#!/usr/bin/php
<?php
/*
 * This is an example hook script
 */
require_once(dirname(__FILE__).'/../../libs/startup.php');

try{

}catch(Exception $e){
    throw new lsException('scripts/hooks/example: Failed', $e);
}
?>
